  SELECT
   AGN.AGN_TAB_IN_CODIGO || '|' || AGN.AGN_PAD_IN_CODIGO || '|' || AGN.AGN_IN_CODIGO || '|' || TAU.AGN_TAU_ST_CODIGO AS ID_AGENTE,
   AGN.AGN_IN_CODIGO AS COD_AGENTE,
   TAU.AGN_TAU_ST_CODIGO AS TIPO_AGENTE,
   TPAGN.TAU_ST_DESCRICAO AS TIPO_AGENTE_DESCRICAO,
   AGN.AGN_BO_CONSOLIDADOR,
   AGN.AGN_ST_NOME AS NOME_AGENTE,
   AGN.AGN_ST_FANTASIA AS FANTASIA_AGENTE,
   AGN.AGN_ST_APELIDO AS APELIDO_AGENTE,
   AGN.AGN_CH_TIPOPESSOAFJ AS TIPO_PESSOA,
   PA.PA_ST_NOME AS PAIS,
   UF.UF_ST_REGIAO AS REGIAO,
   UF.UF_ST_SIGLA AS UF,
   UF.UF_ST_NOME AS NOME_UF,
   MUN.MUN_ST_NOME AS MUNICIPIO,
   MUN.MUN_IN_CODIGOIBGE AS COD_IBGE_MUNICIPIO,
   AGN.AGN_ST_BAIRRO AS BAIRRO,
   AGN.AGN_ST_LOGRADOURO AS LOGRADOURO,
   AGN.AGN_ST_NUMERO AS NUMERO_ENDERECO,
   AGN.AGN_ST_COMPLEMENTO AS COMPLEMENTO_ENDERECO,
   AGN.AGN_ST_CEP AS CEP,
   AGN.AGN_ST_CGC AS CNPJ,
   PF.AGN_ST_CPF AS CPF,
   PF.AGN_ST_RG AS RG,
   PF.AGN_CH_SEXO AS SEXO,
   EC.ECV_ST_DESCRICAO AS ESTADO_CIVIL,
   PF.AGN_DT_NASCIMENTO AS DATA_NASCIMENTO,
   PF.AGN_ST_CONJUGE AS NOME_CONJUGE,
   BAN.BAN_ST_FANTASIA AS BANCO,
   CTA.CTAAGE_ST_NUMERO AS AGENCIA,
   CTA.CTA_ST_NUMERO AS CONTA,
   CAT.CAT_ST_NOME AS CATEGORIA_CONTA,
   OBSAGN.OBSERVACAO
FROM
   CONSTRUCAO.GLO_AGENTES@HACASA AGN
LEFT JOIN
   CONSTRUCAO.GLO_AGENTES_ID@HACASA TAU
   ON (TAU.AGN_TAB_IN_CODIGO = AGN.AGN_TAB_IN_CODIGO
       AND TAU.AGN_PAD_IN_CODIGO = AGN.AGN_PAD_IN_CODIGO
       AND TAU.AGN_IN_CODIGO = AGN.AGN_IN_CODIGO)
LEFT JOIN
   CONSTRUCAO.GLO_TABELAAUX@HACASA TPAGN
   ON (TPAGN.TAU_ST_CODIGO = TAU.AGN_TAU_ST_CODIGO)
LEFT JOIN
   CONSTRUCAO.GLO_PAIS@HACASA PA
   ON (PA.PA_ST_SIGLA = AGN.PA_ST_SIGLA)
LEFT JOIN
   CONSTRUCAO.GLO_UF@HACASA UF
   ON (UF.UF_ST_SIGLA = AGN.UF_ST_SIGLA)
LEFT JOIN
   CONSTRUCAO.GLO_MUNICIPIO@HACASA MUN
   ON (MUN.UF_ST_SIGLA = AGN.UF_ST_SIGLA
       AND MUN.MUN_IN_CODIGO = AGN.MUN_IN_CODIGO)
LEFT JOIN
   CONSTRUCAO.GLO_PESSOA_FISICA@HACASA PF
   ON (PF.AGN_TAB_IN_CODIGO = AGN.AGN_TAB_IN_CODIGO
       AND PF.AGN_PAD_IN_CODIGO = AGN.AGN_PAD_IN_CODIGO
       AND PF.AGN_IN_CODIGO = AGN.AGN_IN_CODIGO
       AND PF.AGN_CH_TIPO = 'P')
LEFT JOIN
   CONSTRUCAO.GLO_ESTADOCIVIL@HACASA EC
   ON (EC.ECV_CH_ESTCIVIL = PF.AGN_CH_ESTCIVIL)
LEFT JOIN
   CONSTRUCAO.GLO_CONTASFIN@HACASA CTA
   ON (CTA.AGN_TAB_IN_CODIGO = TAU.AGN_TAB_IN_CODIGO
       AND CTA.AGN_PAD_IN_CODIGO = TAU.AGN_PAD_IN_CODIGO
       AND CTA.AGN_IN_CODIGO = TAU.AGN_IN_CODIGO
       AND CTA.AGN_TAU_ST_CODIGO = TAU.AGN_TAU_ST_CODIGO)
LEFT JOIN
   CONSTRUCAO.GLO_BANCO@HACASA BAN
   ON (BAN.BAN_IN_NUMERO = CTA.BAN_IN_NUMERO)
LEFT JOIN
   CONSTRUCAO.GLO_CATEGORIA@HACASA CAT
   ON (CAT.CAT_TAB_IN_CODIGO = TAU.CAT_TAB_IN_CODIGO
       AND CAT.CAT_PAD_IN_CODIGO = TAU.CAT_PAD_IN_CODIGO
       AND CAT.CAT_IDE_ST_CODIGO = TAU.CAT_IDE_ST_CODIGO
       AND CAT.CAT_IN_REDUZIDO = TAU.CAT_IN_REDUZIDO)
LEFT JOIN
   CONSTRUCAO.AGENTE_OBS@HACASA OBSAGN
   ON (OBSAGN.AGN_TAB_IN_CODIGO = AGN.AGN_TAB_IN_CODIGO
       AND OBSAGN.AGN_PAD_IN_CODIGO = AGN.AGN_PAD_IN_CODIGO
       AND OBSAGN.AGN_IN_CODIGO = AGN.AGN_IN_CODIGO)
