 SELECT DISTINCT
  WCA.CTO_IN_CODIGO AS CONTRATO,
  EXT.EMP_ST_NOME AS EMPREENDIMENTO,
  EXT.AGN_ST_NOME AS NOME_CLIENTE,
  EXT.BLO_ST_NOME AS BLOCO,
  WPA.PAR_IN_CODIGO AS NUMERO_PARCELA,
  WPA.ANTPAR_DT_VENCIMENTO AS VENCIMENTO,
  WCA.ANT_IN_PARCELAS AS QTD_PARC_ANTECIP,
  WCA.ANT_DT_PRIVENCTO AS PRIMEIRO_VCTO,
  WCA.ANT_DT_ULTVENCTO AS ULTIMO_VCTO,
  WCA.ANT_RE_CAPITALIZADO AS VALOR_CAPTALIZADO,
  WCA.ANT_RE_TAXA AS TAXA,
  WCA.ANT_RE_CORRIGIDO AS VALOR_CORRIGIDO,
  WCA.ANT_RE_DESCONTO AS DESCONTO,
  WCA.ANT_RE_VALORANTECIPADO AS VALOR_ANTECIPADO,
  WCA.ANT_RE_VALORTOTAL AS VALOR_TOTAL,
  WCA.ANT_RE_VALORLIQUIDO AS VALOR_LIQUIDO,
  WCA.ANT_DT_MOVIMENTO AS DT_MOVIMENTO,
  WCA.ANT_DT_BAIXA AS DT_BAIXA,
  WCA.ANT_CH_STATUS AS STATUS
FROM
  CONSTRUCAO.WCAR_ANTECIPACAO@HACASA WCA
JOIN
  CONSTRUCAO.WCAR_ANTECIPACAO_PARCELA@HACASA WPA
  ON WCA.ORG_TAB_IN_CODIGO = WPA.ORG_TAB_IN_CODIGO
  AND WCA.ORG_PAD_IN_CODIGO = WPA.ORG_PAD_IN_CODIGO
  AND WCA.ORG_TAU_ST_CODIGO = WPA.ORG_TAU_ST_CODIGO
  AND WCA.ORG_IN_CODIGO = WPA.ORG_IN_CODIGO
  AND WCA.ANT_IN_CODIGO = WPA.ANT_IN_CODIGO
  AND WCA.CTO_IN_CODIGO = WPA.CTO_IN_CODIGO
JOIN
  CONSTRUCAO.CAR_DW_PARCELA@HACASA EXT
  ON WPA.ORG_TAB_IN_CODIGO = EXT.ORG_TAB_IN_CODIGO
  AND WPA.ORG_PAD_IN_CODIGO = EXT.ORG_PAD_IN_CODIGO
  AND WPA.ORG_TAU_ST_CODIGO = EXT.ORG_TAU_ST_CODIGO
  AND WPA.ORG_IN_CODIGO = EXT.ORG_IN_CODIGO
  AND WPA.CTO_IN_CODIGO = EXT.CTO_IN_CODIGO