  SELECT ALC.NUMERO_DOCUMENTO, ALC.PAI_NUMERO_DOCUMENTO AS NUM_CONT, ALC.NOME_FILIAL, ALC.NOME_AGENTE, ALC.NOME_SOLICITANTE, ALC.VALOR_DOCUMENTO, ALC.DATA_DOCUMENTO, OCO.DATA_OCORRENCIA AS DATA_APROVACAO, OCO.NOME_APROVADOR AS APROVADO_POR
FROM CONSTRUCAO.WGLO_ALCADA_DOCUMENTO@HACASA ALC,
CONSTRUCAO.WGLO_ALCADA_OCORRENCIA@HACASA OCO
WHERE ALC.DOC_IN_CODIGO = OCO.DOC_IN_CODIGO AND
      ALC.STATUS_DOCUMENTO = 'A'