 SELECT A.ACAO_TAB_IN_CODIGO||'|'||A.ACAO_PAD_IN_CODIGO||'|'||A.ACAO_IN_CODIGO AS ID_ACAO,
       A.PAI_ACAO_TAB_IN_CODIGO||'|'||A.PAI_ACAO_PAD_IN_CODIGO||'|'||A.PAI_ACAO_IN_CODIGO AS ID_ACAO_PAI,
       A.ACAO_IN_CODIGO AS COD_ACAO,
       A.ACAO_ST_NOME AS NOME_ACAO,
       A.ACAO_ST_TIPO AS TIPO_ACAO,
       A.ACAO_ST_ENTSAI AS ENTRADA_SAIDA
  FROM CONSTRUCAO.GLO_ACAO@HACASA A