SELECT L.ORG_TAB_IN_CODIGO,
     L.ORG_PAD_IN_CODIGO,
     L.ORG_IN_CODIGO,
     I.FIL_IN_CODIGO,
     L.ORG_TAU_ST_CODIGO,
     L.LOT_TAB_IN_CODIGO,
     L.LOT_SEQ_IN_CODIGO,
     L.LOT_IN_CODIGO,
     L.LAN_TAB_IN_CODIGO,
     L.LAN_SEQ_IN_CODIGO,
     L.LAN_IN_CODIGO,
     L.LAN_IN_LANCMES,
     L.LAN_CH_STATUS,
     I.LAN_DT_LANCAMENTO,
     L.IND_IN_CODIGO,
     L.SIS_IN_CODIGO,
     L.TLA_IN_CODIGO,
     L.ACAO_TAB_IN_CODIGO,
     L.ACAO_PAD_IN_CODIGO,
     L.ACAO_IN_CODIGO,
     L.ACAOM_IN_SEQUENCIA,
     L.LAN_CH_TIPOCONTAB,
     LV.CRI_IN_CODIGO,
     I.ITE_IN_CODIGO,
     I.ITE_DT_CONVERSAO,
     I.ITE_RE_VALOR,
     I.DEB_IDE_ST_CODIGO,
     I.DEB_IN_REDUZIDO,
     I.ITE_CH_CONCBAN,
     I.ITE_CH_CONCCON,
     I.USU_IN_INCLUSAO,
     I.ITE_DT_INCLUSAO,
     I.USU_IN_ALTERACAO,
     I.ITE_DT_ULTALTERACAO,
     I.HIS_TAB_IN_CODIGO,
     I.HIS_PAD_IN_CODIGO,
     I.HIS_IDE_ST_CODIGO,
     I.HIS_IN_REDUZIDO,
     I.ITE_ST_DOCUMENTO,
     I.ITE_ST_CONCILIACAO,
     I.ITE_ST_REFERENCIA,
     I.ITE_IN_ORIGEM,
     I.ITE_ST_DOCORIGEM,
     PC.PLA_ST_EXTENSO,
     PC.PLA_CH_TIPO_CONTA,
     PC.PLA_ST_DESCRICAO,
     PC.PLA_DT_ULT_MOV,
     PC.PLA_DT_LIMITE,
     H.HIS_ST_EXTENSO,
     H.HIS_ST_APELIDO,
     H.HIS_CH_TIPO_CONTA,
     H.HIS_ST_DESCRICAO,
     H.HIS_DT_LIMITE,
     --decode(H.HIS_CH_ATIVADO, null, 'S', H.HIS_CH_ATIVADO),
     PC.PLA_CH_CENTROCUSTO,
     PC.PLA_CH_PROJETO,
     PC.PLA_CH_FILIAL,
     PC.PLA_CH_ATIVADO,
     PC.PLA_ST_APELIDO,
     PC.PLA_IN_NIVEL,
     PC.PLA_DT_IMPLANTACAO,
     PC.PLA_CH_TIPO_DEMO,
     PC.PLA_CH_SINAL,
     I.PLA_TAB_IN_CODIGO,
     I.PLA_PAD_IN_CODIGO,
     I.ITE_DT_ORCAMENTO,
     I.TPD_ST_CODIGO,
     CC.CUS_CH_ATIVADO,
     PR.PRO_BO_ATIVADOSALDO,
     LPR.RPRO_CH_NATUREZA,
     LPR.RPRO_RE_VALOR,
     LCC.LCC_IN_SEQUENCIAL,
     LCC.LCC_CH_NATUREZA,
     LCC.CUS_TAB_IN_CODIGO,
     LCC.CUS_PAD_IN_CODIGO,
     LCC.CUS_IDE_ST_CODIGO,
     LCC.CUS_IN_REDUZIDO,
     LPR.PRO_TAB_IN_CODIGO,
     LPR.PRO_PAD_IN_CODIGO,
     LPR.PRO_IDE_ST_CODIGO,
     LPR.PRO_IN_REDUZIDO,
     LV.VPRO_RE_VALOR,
     0 VALID
FROM
     CONSTRUCAO.CON_ITEM_LANCAMENTO@HACASA I,
     CONSTRUCAO.CON_LANCAMENTO@HACASA      L,
     CONSTRUCAO.CON_PLANO_CONTA@HACASA     PC,
     CONSTRUCAO.CON_HISTORICO@HACASA       H,
     CONSTRUCAO.CON_LANCAMENTO_CC@HACASA   LCC,
     CONSTRUCAO.CON_LANCAMENTO_PRO@HACASA  LPR,
     CONSTRUCAO.CON_CENTRO_CUSTO@HACASA    CC,
     CONSTRUCAO.GLO_PROJETOS@HACASA        PR,
     CONSTRUCAO.CON_VALORESLANPRO@HACASA   LV
  WHERE L.ORG_TAB_IN_CODIGO     = I.ORG_TAB_IN_CODIGO
 and L.ORG_PAD_IN_CODIGO     = I.ORG_PAD_IN_CODIGO
 and L.ORG_IN_CODIGO         = I.ORG_IN_CODIGO
 and L.ORG_TAU_ST_CODIGO     = I.ORG_TAU_ST_CODIGO
 and L.LAN_TAB_IN_CODIGO     = I.LAN_TAB_IN_CODIGO
 and L.LAN_SEQ_IN_CODIGO     = I.LAN_SEQ_IN_CODIGO
 and L.LAN_IN_CODIGO         = I.LAN_IN_CODIGO
 and PC.PLA_TAB_IN_CODIGO    = I.PLA_TAB_IN_CODIGO
 and PC.PLA_PAD_IN_CODIGO    = I.PLA_PAD_IN_CODIGO
 and PC.PLA_IDE_ST_CODIGO    = I.DEB_IDE_ST_CODIGO
 and PC.PLA_IN_REDUZIDO      = I.DEB_IN_REDUZIDO
 and H.HIS_TAB_IN_CODIGO (+) = I.HIS_TAB_IN_CODIGO
 and H.HIS_PAD_IN_CODIGO (+) = I.HIS_PAD_IN_CODIGO
 and H.HIS_IDE_ST_CODIGO (+) = I.HIS_IDE_ST_CODIGO
 and H.HIS_IN_REDUZIDO   (+) = I.HIS_IN_REDUZIDO
 and I.ORG_TAB_IN_CODIGO     = LCC.ORG_TAB_IN_CODIGO
 and I.ORG_PAD_IN_CODIGO     = LCC.ORG_PAD_IN_CODIGO
 and I.ORG_IN_CODIGO         = LCC.ORG_IN_CODIGO
 and I.ORG_TAU_ST_CODIGO     = LCC.ORG_TAU_ST_CODIGO
 and I.LAN_TAB_IN_CODIGO     = LCC.LAN_TAB_IN_CODIGO
 and I.LAN_SEQ_IN_CODIGO     = LCC.LAN_SEQ_IN_CODIGO
 and I.LAN_IN_CODIGO         = LCC.LAN_IN_CODIGO
 and I.ITE_IN_CODIGO         = LCC.ITE_IN_CODIGO
 and LCC.ORG_TAB_IN_CODIGO   = LPR.ORG_TAB_IN_CODIGO
 and LCC.ORG_PAD_IN_CODIGO   = LPR.ORG_PAD_IN_CODIGO
 and LCC.ORG_IN_CODIGO       = LPR.ORG_IN_CODIGO
 and LCC.ORG_TAU_ST_CODIGO   = LPR.ORG_TAU_ST_CODIGO
 and LCC.LAN_TAB_IN_CODIGO   = LPR.LAN_TAB_IN_CODIGO
 and LCC.LAN_SEQ_IN_CODIGO   = LPR.LAN_SEQ_IN_CODIGO
 and LCC.LAN_IN_CODIGO       = LPR.LAN_IN_CODIGO
 and LCC.ITE_IN_CODIGO       = LPR.ITE_IN_CODIGO
 and LCC.LCC_CH_NATUREZA     = LPR.LCC_CH_NATUREZA
 and LCC.LCC_IN_SEQUENCIAL   = LPR.LCC_IN_SEQUENCIAL
 and LCC.CUS_TAB_IN_CODIGO   = CC.CUS_TAB_IN_CODIGO
 and LCC.CUS_PAD_IN_CODIGO   = CC.CUS_PAD_IN_CODIGO
 and LCC.CUS_IDE_ST_CODIGO   = CC.CUS_IDE_ST_CODIGO
 and LCC.CUS_IN_REDUZIDO     = CC.CUS_IN_REDUZIDO
 and LPR.PRO_TAB_IN_CODIGO   = PR.PRO_TAB_IN_CODIGO
 and LPR.PRO_PAD_IN_CODIGO   = PR.PRO_PAD_IN_CODIGO
 and LPR.PRO_IDE_ST_CODIGO   = PR.PRO_IDE_ST_CODIGO
 and LPR.PRO_IN_REDUZIDO     = PR.PRO_IN_REDUZIDO
 and LPR.ORG_TAB_IN_CODIGO   = LV.ORG_TAB_IN_CODIGO (+)
 and LPR.ORG_PAD_IN_CODIGO   = LV.ORG_PAD_IN_CODIGO (+)
 and LPR.ORG_IN_CODIGO       = LV.ORG_IN_CODIGO     (+)
 and LPR.ORG_TAU_ST_CODIGO   = LV.ORG_TAU_ST_CODIGO (+)
 and LPR.LAN_TAB_IN_CODIGO   = LV.LAN_TAB_IN_CODIGO (+)
 and LPR.LAN_SEQ_IN_CODIGO   = LV.LAN_SEQ_IN_CODIGO (+)
 and LPR.LAN_IN_CODIGO       = LV.LAN_IN_CODIGO     (+)
 and LPR.ITE_IN_CODIGO       = LV.ITE_IN_CODIGO     (+)
 and LPR.LCC_IN_SEQUENCIAL   = LV.LCC_IN_SEQUENCIAL (+)
 and LPR.LCC_CH_NATUREZA     = LV.LCC_CH_NATUREZA   (+)
 and LPR.PRO_TAB_IN_CODIGO   = LV.PRO_TAB_IN_CODIGO (+)
 and LPR.PRO_PAD_IN_CODIGO   = LV.PRO_PAD_IN_CODIGO (+)
 and LPR.PRO_IDE_ST_CODIGO   = LV.PRO_IDE_ST_CODIGO (+)
 and LPR.PRO_IN_REDUZIDO     = LV.PRO_IN_REDUZIDO   (+)
 and LPR.RPRO_CH_NATUREZA    = LV.RPRO_CH_NATUREZA  (+)
 and LCC.LCC_CH_NATUREZA     = 'D'
 and LPR.RPRO_CH_NATUREZA    = 'D'
 and L.LAN_CH_STATUS         = 'A'
UNION
SELECT
     L.ORG_TAB_IN_CODIGO,
     L.ORG_PAD_IN_CODIGO,
     L.ORG_IN_CODIGO,
     I.FIL_IN_CODIGO,
     L.ORG_TAU_ST_CODIGO,
     L.LOT_TAB_IN_CODIGO,
     L.LOT_SEQ_IN_CODIGO,
     L.LOT_IN_CODIGO,
     L.LAN_TAB_IN_CODIGO,
     L.LAN_SEQ_IN_CODIGO,
     L.LAN_IN_CODIGO,
     L.LAN_IN_LANCMES,
     L.LAN_CH_STATUS,
     I.LAN_DT_LANCAMENTO,
     L.IND_IN_CODIGO,
     L.SIS_IN_CODIGO,
     L.TLA_IN_CODIGO,
     L.ACAO_TAB_IN_CODIGO,
     L.ACAO_PAD_IN_CODIGO,
     L.ACAO_IN_CODIGO,
     L.ACAOM_IN_SEQUENCIA,
     L.LAN_CH_TIPOCONTAB,
     LV.CRI_IN_CODIGO,
     I.ITE_IN_CODIGO,
     I.ITE_DT_CONVERSAO,
     I.ITE_RE_VALOR,
     I.CRE_IDE_ST_CODIGO,
     I.CRE_IN_REDUZIDO,
     I.ITE_CH_CONCBAN,
     I.ITE_CH_CONCCON,
     I.USU_IN_INCLUSAO,
     I.ITE_DT_INCLUSAO,
     I.USU_IN_ALTERACAO,
     I.ITE_DT_ULTALTERACAO,
     I.HIS_TAB_IN_CODIGO,
     I.HIS_PAD_IN_CODIGO,
     I.HIS_IDE_ST_CODIGO,
     I.HIS_IN_REDUZIDO,
     I.ITE_ST_DOCUMENTO,
     I.ITE_ST_CONCILIACAO,
     I.ITE_ST_REFERENCIA,
     I.ITE_IN_ORIGEM,
     I.ITE_ST_DOCORIGEM,
     PC.PLA_ST_EXTENSO,
     PC.PLA_CH_TIPO_CONTA,
     PC.PLA_ST_DESCRICAO,
     PC.PLA_DT_ULT_MOV,
     PC.PLA_DT_LIMITE,
     H.HIS_ST_EXTENSO,
     H.HIS_ST_APELIDO,
     H.HIS_CH_TIPO_CONTA,
     H.HIS_ST_DESCRICAO,
     H.HIS_DT_LIMITE,
     --decode(H.HIS_CH_ATIVADO, null, 'S', H.HIS_CH_ATIVADO),
     PC.PLA_CH_CENTROCUSTO,
     PC.PLA_CH_PROJETO,
     PC.PLA_CH_FILIAL,
     PC.PLA_CH_ATIVADO,
     PC.PLA_ST_APELIDO,
     PC.PLA_IN_NIVEL,
     PC.PLA_DT_IMPLANTACAO,
     PC.PLA_CH_TIPO_DEMO,
     PC.PLA_CH_SINAL,
     I.PLA_TAB_IN_CODIGO,
     I.PLA_PAD_IN_CODIGO,
     I.ITE_DT_ORCAMENTO,
     I.TPD_ST_CODIGO,
     CC.CUS_CH_ATIVADO,
     PR.PRO_BO_ATIVADOSALDO,
     LPR.RPRO_CH_NATUREZA,
     LPR.RPRO_RE_VALOR,
     LCC.LCC_IN_SEQUENCIAL,
     LCC.LCC_CH_NATUREZA,
     LCC.CUS_TAB_IN_CODIGO,
     LCC.CUS_PAD_IN_CODIGO,
     LCC.CUS_IDE_ST_CODIGO,
     LCC.CUS_IN_REDUZIDO,
     LPR.PRO_TAB_IN_CODIGO,
     LPR.PRO_PAD_IN_CODIGO,
     LPR.PRO_IDE_ST_CODIGO,
     LPR.PRO_IN_REDUZIDO,
     0 VALID,
     LV.VPRO_RE_VALOR
from
     CONSTRUCAO.CON_ITEM_LANCAMENTO@HACASA I,
     CONSTRUCAO.CON_LANCAMENTO@HACASA      L,
     CONSTRUCAO.CON_PLANO_CONTA@HACASA     PC,
     CONSTRUCAO.CON_HISTORICO@HACASA       H,
     CONSTRUCAO.CON_LANCAMENTO_CC@HACASA   LCC,
     CONSTRUCAO.CON_LANCAMENTO_PRO@HACASA  LPR,
     CONSTRUCAO.CON_CENTRO_CUSTO@HACASA    CC,
     CONSTRUCAO.GLO_PROJETOS@HACASA        PR,
     CONSTRUCAO.CON_VALORESLANPRO@HACASA   LV
where
     L.ORG_TAB_IN_CODIGO     = I.ORG_TAB_IN_CODIGO
 and L.ORG_PAD_IN_CODIGO     = I.ORG_PAD_IN_CODIGO
 and L.ORG_IN_CODIGO         = I.ORG_IN_CODIGO
 and L.ORG_TAU_ST_CODIGO     = I.ORG_TAU_ST_CODIGO
 and L.LAN_TAB_IN_CODIGO     = I.LAN_TAB_IN_CODIGO
 and L.LAN_SEQ_IN_CODIGO     = I.LAN_SEQ_IN_CODIGO
 and L.LAN_IN_CODIGO         = I.LAN_IN_CODIGO
 and PC.PLA_TAB_IN_CODIGO    = I.PLA_TAB_IN_CODIGO
 and PC.PLA_PAD_IN_CODIGO    = I.PLA_PAD_IN_CODIGO
 and PC.PLA_IDE_ST_CODIGO    = I.CRE_IDE_ST_CODIGO
 and PC.PLA_IN_REDUZIDO      = I.CRE_IN_REDUZIDO
 and H.HIS_TAB_IN_CODIGO (+) = I.HIS_TAB_IN_CODIGO
 and H.HIS_PAD_IN_CODIGO (+) = I.HIS_PAD_IN_CODIGO
 and H.HIS_IDE_ST_CODIGO (+) = I.HIS_IDE_ST_CODIGO
 and H.HIS_IN_REDUZIDO   (+) = I.HIS_IN_REDUZIDO
 and I.ORG_TAB_IN_CODIGO     = LCC.ORG_TAB_IN_CODIGO
 and I.ORG_PAD_IN_CODIGO     = LCC.ORG_PAD_IN_CODIGO
 and I.ORG_IN_CODIGO         = LCC.ORG_IN_CODIGO
 and I.ORG_TAU_ST_CODIGO     = LCC.ORG_TAU_ST_CODIGO
 and I.LAN_TAB_IN_CODIGO     = LCC.LAN_TAB_IN_CODIGO
 and I.LAN_SEQ_IN_CODIGO     = LCC.LAN_SEQ_IN_CODIGO
 and I.LAN_IN_CODIGO         = LCC.LAN_IN_CODIGO
 and I.ITE_IN_CODIGO         = LCC.ITE_IN_CODIGO
 and LCC.ORG_TAB_IN_CODIGO   = LPR.ORG_TAB_IN_CODIGO
 and LCC.ORG_PAD_IN_CODIGO   = LPR.ORG_PAD_IN_CODIGO
 and LCC.ORG_IN_CODIGO       = LPR.ORG_IN_CODIGO
 and LCC.ORG_TAU_ST_CODIGO   = LPR.ORG_TAU_ST_CODIGO
 and LCC.LAN_TAB_IN_CODIGO   = LPR.LAN_TAB_IN_CODIGO
 and LCC.LAN_SEQ_IN_CODIGO   = LPR.LAN_SEQ_IN_CODIGO
 and LCC.LAN_IN_CODIGO       = LPR.LAN_IN_CODIGO
 and LCC.ITE_IN_CODIGO       = LPR.ITE_IN_CODIGO
 and LCC.LCC_CH_NATUREZA     = LPR.LCC_CH_NATUREZA
 and LCC.LCC_IN_SEQUENCIAL   = LPR.LCC_IN_SEQUENCIAL
 and LCC.CUS_TAB_IN_CODIGO   = CC.CUS_TAB_IN_CODIGO
 and LCC.CUS_PAD_IN_CODIGO   = CC.CUS_PAD_IN_CODIGO
 and LCC.CUS_IDE_ST_CODIGO   = CC.CUS_IDE_ST_CODIGO
 and LCC.CUS_IN_REDUZIDO     = CC.CUS_IN_REDUZIDO
 and LPR.PRO_TAB_IN_CODIGO   = PR.PRO_TAB_IN_CODIGO
 and LPR.PRO_PAD_IN_CODIGO   = PR.PRO_PAD_IN_CODIGO
 and LPR.PRO_IDE_ST_CODIGO   = PR.PRO_IDE_ST_CODIGO
 and LPR.PRO_IN_REDUZIDO     = PR.PRO_IN_REDUZIDO
 and LPR.ORG_TAB_IN_CODIGO   = LV.ORG_TAB_IN_CODIGO (+)
 and LPR.ORG_PAD_IN_CODIGO   = LV.ORG_PAD_IN_CODIGO (+)
 and LPR.ORG_IN_CODIGO       = LV.ORG_IN_CODIGO     (+)
 and LPR.ORG_TAU_ST_CODIGO   = LV.ORG_TAU_ST_CODIGO (+)
 and LPR.LAN_TAB_IN_CODIGO   = LV.LAN_TAB_IN_CODIGO (+)
 and LPR.LAN_SEQ_IN_CODIGO   = LV.LAN_SEQ_IN_CODIGO (+)
 and LPR.LAN_IN_CODIGO       = LV.LAN_IN_CODIGO     (+)
 and LPR.ITE_IN_CODIGO       = LV.ITE_IN_CODIGO     (+)
 and LPR.LCC_IN_SEQUENCIAL   = LV.LCC_IN_SEQUENCIAL (+)
 and LPR.LCC_CH_NATUREZA     = LV.LCC_CH_NATUREZA   (+)
 and LPR.PRO_TAB_IN_CODIGO   = LV.PRO_TAB_IN_CODIGO (+)
 and LPR.PRO_PAD_IN_CODIGO   = LV.PRO_PAD_IN_CODIGO (+)
 and LPR.PRO_IDE_ST_CODIGO   = LV.PRO_IDE_ST_CODIGO (+)
 and LPR.PRO_IN_REDUZIDO     = LV.PRO_IN_REDUZIDO   (+)
 and LPR.RPRO_CH_NATUREZA    = LV.RPRO_CH_NATUREZA  (+)
 and LCC.LCC_CH_NATUREZA     = 'C'
 and LPR.RPRO_CH_NATUREZA    = 'C'
 and L.LAN_CH_STATUS         = 'A'