 SELECT I.ITE_IN_CODIGO ITE_IN_CODIGO
          ,I.PLA_PAD_IN_CODIGO PLA_PAD_IN_CODIGO
          ,I.ITE_DT_CONVERSAO ITE_DT_CONVERSAO
          ,I.ITE_RE_VALOR ITE_RE_VALOR
          ,I.PLA_TAB_IN_CODIGO PLA_TAB_IN_CODIGO
          ,I.CRE_IDE_ST_CODIGO CRE_IDE_ST_CODIGO
          ,I.CRE_IN_REDUZIDO CRE_IN_REDUZIDO
          ,I.DEB_IDE_ST_CODIGO DEB_IDE_ST_CODIGO
          ,I.DEB_IN_REDUZIDO DEB_IN_REDUZIDO
          ,I.HIS_TAB_IN_CODIGO HIS_TAB_IN_CODIGO
          ,I.HIS_PAD_IN_CODIGO HIS_PAD_IN_CODIGO
          ,I.HIS_IDE_ST_CODIGO HIS_IDE_ST_CODIGO
          ,I.HIS_IN_REDUZIDO HIS_IN_REDUZIDO
          ,P.PRO_TAB_IN_CODIGO PRO_TAB_IN_CODIGO
          ,P.PRO_PAD_IN_CODIGO PRO_PAD_IN_CODIGO
          ,P.PRO_IDE_ST_CODIGO PRO_IDE_ST_CODIGO
          ,P.PRO_IN_REDUZIDO PRO_IN_REDUZIDO
          ,P.RPRO_CH_NATUREZA RPRO_CH_NATUREZA
          ,P.RPRO_RE_VALOR RPRO_RE_VALOR
          ,P.RPRO_RE_PERCENTUAL RPRO_RE_PERCENTUAL
          ,L.ORG_TAB_IN_CODIGO ORG_TAB_IN_CODIGO
          ,L.ORG_PAD_IN_CODIGO ORG_PAD_IN_CODIGO
          ,L.ORG_IN_CODIGO ORG_IN_CODIGO
          ,L.ORG_TAU_ST_CODIGO ORG_TAU_ST_CODIGO
          ,L.LAN_TAB_IN_CODIGO LAN_TAB_IN_CODIGO
          ,L.LAN_SEQ_IN_CODIGO LAN_SEQ_IN_CODIGO
          ,L.LAN_IN_CODIGO LAN_IN_CODIGO
          ,L.IND_IN_CODIGO IND_IN_CODIGO
          ,L.ACAO_TAB_IN_CODIGO ACAO_TAB_IN_CODIGO
          ,L.ACAO_PAD_IN_CODIGO ACAO_PAD_IN_CODIGO
          ,L.ACAO_IN_CODIGO ACAO_IN_CODIGO
          ,L.ACAOM_IN_SEQUENCIA ACAOM_IN_SEQUENCIA
          ,L.LOT_TAB_IN_CODIGO LOT_TAB_IN_CODIGO
          ,L.LOT_SEQ_IN_CODIGO LOT_SEQ_IN_CODIGO
          ,L.LOT_IN_CODIGO LOT_IN_CODIGO
          ,L.LAN_CH_STATUS LAN_CH_STATUS
          ,I.LAN_DT_LANCAMENTO LAN_DT_LANCAMENTO
          ,I.ITE_DT_ORCAMENTO ITE_DT_ORCAMENTO
          ,L.SIS_IN_CODIGO SIS_IN_CODIGO
          ,L.TLA_IN_CODIGO TLA_IN_CODIGO
          ,L.LAN_IN_ANOMES LAN_IN_ANOMES
          ,L.LAN_IN_LANCMES LAN_IN_LANCMES
          ,C.LCC_CH_NATUREZA LCC_CH_NATUREZA
          ,C.LCC_IN_SEQUENCIAL LCC_IN_SEQUENCIAL
          ,C.CUS_TAB_IN_CODIGO CUS_TAB_IN_CODIGO
          ,C.CUS_PAD_IN_CODIGO CUS_PAD_IN_CODIGO
          ,C.CUS_IDE_ST_CODIGO CUS_IDE_ST_CODIGO
          ,C.CUS_IN_REDUZIDO CUS_IN_REDUZIDO
          ,C.LCC_RE_VALOR LCC_RE_VALOR
          ,C.LCC_RE_PERCENTUAL LCC_RE_PERCENTUAL
          ,I.FIL_IN_CODIGO FIL_IN_CODIGO
          ,A.ACAO_BO_ORCAMENTO ACAO_BO_ORCAMENTO
          ,I.AGN_TAB_IN_CODIGO AGN_TAB_IN_CODIGO
          ,I.AGN_PAD_IN_CODIGO AGN_PAD_IN_CODIGO
          ,I.AGN_IN_CODIGO AGN_IN_CODIGO
          ,I.ITE_DT_ATUORCAMENTO
          ,I.ITE_ST_DOCUMENTO
          ,I.ITE_ST_COMPLEMENTO
          ,L.LAN_CH_TIPOCONTAB 
          ,L.LAN_CH_TIPOCONTABUSU 
FROM CONSTRUCAO.CON_ITEM_LANCAMENTO@HACASA I
    ,CONSTRUCAO.CON_LANCAMENTO_PRO@HACASA P
    ,CONSTRUCAO.CON_LANCAMENTO@HACASA L
    ,CONSTRUCAO.CON_LANCAMENTO_CC@HACASA C
    ,CONSTRUCAO.GLO_ACAO@HACASA A
  WHERE L.ORG_TAB_IN_CODIGO = I.ORG_TAB_IN_CODIGO and
        L.ORG_PAD_IN_CODIGO = I.ORG_PAD_IN_CODIGO and
        L.ORG_IN_CODIGO = I.ORG_IN_CODIGO and
        L.ORG_TAU_ST_CODIGO = I.ORG_TAU_ST_CODIGO and
        L.LAN_TAB_IN_CODIGO = I.LAN_TAB_IN_CODIGO and
        L.LAN_SEQ_IN_CODIGO = I.LAN_SEQ_IN_CODIGO and
        L.LAN_IN_CODIGO = I.LAN_IN_CODIGO and
        L.ACAO_TAB_IN_CODIGO = A.ACAO_TAB_IN_CODIGO and
        L.ACAO_PAD_IN_CODIGO = A.ACAO_PAD_IN_CODIGO and
        L.ACAO_IN_CODIGO = A.ACAO_IN_CODIGO and
        I.ORG_TAB_IN_CODIGO = C.ORG_TAB_IN_CODIGO and
        I.ORG_PAD_IN_CODIGO = C.ORG_PAD_IN_CODIGO and
        I.ORG_IN_CODIGO = C.ORG_IN_CODIGO and
        I.ORG_TAU_ST_CODIGO = C.ORG_TAU_ST_CODIGO and
        I.LAN_TAB_IN_CODIGO = C.LAN_TAB_IN_CODIGO and
        I.LAN_SEQ_IN_CODIGO = C.LAN_SEQ_IN_CODIGO and
        I.LAN_IN_CODIGO = C.LAN_IN_CODIGO and
        I.ITE_IN_CODIGO = C.ITE_IN_CODIGO and
        C.ORG_TAB_IN_CODIGO = P.ORG_TAB_IN_CODIGO and
        C.ORG_PAD_IN_CODIGO = P.ORG_PAD_IN_CODIGO and
        C.ORG_IN_CODIGO = P.ORG_IN_CODIGO and
        C.ORG_TAU_ST_CODIGO = P.ORG_TAU_ST_CODIGO and
        C.LAN_TAB_IN_CODIGO = P.LAN_TAB_IN_CODIGO and
        C.LAN_SEQ_IN_CODIGO = P.LAN_SEQ_IN_CODIGO and
        C.LAN_IN_CODIGO = P.LAN_IN_CODIGO and
        C.ITE_IN_CODIGO = P.ITE_IN_CODIGO and
        C.LCC_CH_NATUREZA = P.LCC_CH_NATUREZA and
        C.LCC_IN_SEQUENCIAL = P.LCC_IN_SEQUENCIAL