 select PLA.PLA_ST_EXTENSO,
       PLA.PLA_IN_REDUZIDO,
       PLA.PLA_ST_DESCRICAO,
       PLA.PLA_IN_NIVEL,
       PLA.PLA_CH_TIPO_DEMO,
       CUS.CUS_IN_REDUZIDO,
       CUS.CUS_ST_EXTENSO,
       CUS.CUS_ST_DESCRICAO,
       CUS.CUS_IN_NIVEL,
       PRO.PRO_ST_EXTENSO,
       PRO.PRO_IN_REDUZIDO,
       PRO.PRO_ST_DESCRICAO,
       PRO.PRO_IN_NIVEL,
       AGN.AGN_IN_CODIGO,
       AGN.AGN_ST_NOME,
       ORG.ORG_IN_CODIGO,
       ORG.ORG_ST_NOME,
       BAL.BAL_RE_VAL1,
       BAL.BAL_RE_VAL2,
       BAL.BAL_RE_VAL3,
       BAL.BAL_RE_VAL4,
       BAL.BAL_RE_VAL5,
       BAL.BAL_RE_VAL6,
       BAL.BAL_RE_VAL7,
       BAL.BAL_RE_VAL8,
       BAL.BAL_RE_VAL9,
       BAL.BAL_RE_VAL10,
       BAL.BAL_RE_VAL11,
       BAL.BAL_RE_VAL12,
       BAL.BAL_RE_VAL13,
       BAL.BAL_RE_VAL14,
       BAL.BAL_RE_VAL15,
       BAL.BAL_RE_VAL16,
       BAL.BAL_RE_VAL17,
       BAL.BAL_RE_VAL18,
       BAL.BAL_RE_VAL19,
       BAL.BAL_RE_VAL20,
       BAL.BAL_RE_VAL21,
       BAL.BAL_RE_VAL22,
       BAL.BAL_RE_VAL23,
       BAL.BAL_RE_VAL24,
       BAL.BAL_RE_VAL25,
       BAL.BAL_RE_VAL26,
       BAL.BAL_RE_VAL27,
       BAL.BAL_RE_VAL28,
       BAL.BAL_RE_VAL29,
       BAL.BAL_RE_VAL30,
       BAL.BAL_RE_VAL31,
       BAL.BAL_CH_TIPO,
       BAL.BAL_ST_ORDEM,
       BAL.BAL_IN_CHAVE,
       BAL.COMP_ST_NOME
  from construcao.CON_BALANCETE@hacasa BAL,
       construcao.CON_PLANO_CONTA@hacasa PLA,
       construcao.CON_CENTRO_CUSTO@hacasa CUS,
       construcao.GLO_PROJETOS@hacasa PRO,
       construcao.GLO_AGENTES@hacasa AGN,
       construcao.GLO_VW_ORGANIZACAO@hacasa ORG
 where BAL.PLA_TAB_IN_CODIGO = PLA.PLA_TAB_IN_CODIGO (+)
   and BAL.PLA_PAD_IN_CODIGO = PLA.PLA_PAD_IN_CODIGO (+)
   and BAL.PLA_IDE_ST_CODIGO = PLA.PLA_IDE_ST_CODIGO (+)
   and BAL.PLA_IN_REDUZIDO   = PLA.PLA_IN_REDUZIDO   (+)
   and BAL.CUS_TAB_IN_CODIGO = CUS.CUS_TAB_IN_CODIGO (+)
   and BAL.CUS_PAD_IN_CODIGO = CUS.CUS_PAD_IN_CODIGO (+)
   and BAL.CUS_IDE_ST_CODIGO = CUS.CUS_IDE_ST_CODIGO (+)
   and BAL.CUS_IN_REDUZIDO   = CUS.CUS_IN_REDUZIDO   (+)
   and BAL.PRO_TAB_IN_CODIGO = PRO.PRO_TAB_IN_CODIGO (+)
   and BAL.PRO_PAD_IN_CODIGO = PRO.PRO_PAD_IN_CODIGO (+)
   and BAL.PRO_IDE_ST_CODIGO = PRO.PRO_IDE_ST_CODIGO (+)
   and BAL.PRO_IN_REDUZIDO   = PRO.PRO_IN_REDUZIDO   (+)
   and BAL.ORG_TAB_IN_CODIGO = ORG.ORG_TAB_IN_CODIGO (+)
   and BAL.ORG_PAD_IN_CODIGO = ORG.ORG_PAD_IN_CODIGO (+)
   and BAL.ORG_IN_CODIGO     = ORG.ORG_IN_CODIGO     (+)
   and BAL.AGN_TAB_IN_CODIGO = AGN.AGN_TAB_IN_CODIGO (+)
   and BAL.AGN_PAD_IN_CODIGO = AGN.AGN_PAD_IN_CODIGO (+)
   and BAL.AGN_IN_CODIGO     = AGN.AGN_IN_CODIGO     (+)
 order by nlssort(BAL_ST_ORDEM, 'NLS_SORT = binary')