  SELECT 
IPF.LAN_IN_CODIGO,
IPF.LAN_TAB_IN_CODIGO,
IPF.LCC_CH_NATUREZA,
IPF.ORG_IN_CODIGO,
IPF.ORG_PAD_IN_CODIGO,
IPF.ORG_TAB_IN_CODIGO,
IPF.ORG_TAU_ST_CODIGO,
IPF.RPRO_CH_NATUREZA,
IPF.RPRO_DT_INCLUSAO,
IPF.PRO_IN_REDUZIDO,
PJT.PRO_ST_EXTENSO,
PJT.PRO_ST_DESCRICAO,
IPF.RPRO_DT_ULTALTERACAO,
IPF.RPRO_RE_PERCENTUAL,
IPF.RPRO_RE_VALOR,
IPF.USU_IN_ALTERACAO,
IPF.USU_IN_INCLUSAO
FROM CONSTRUCAO.CON_LANCAMENTO_PRO@HACASA IPF,
     CONSTRUCAO.GLO_PROJETOS@HACASA PJT
WHERE IPF.PRO_IN_REDUZIDO = PJT.PRO_IN_REDUZIDO AND
      IPF.PRO_PAD_IN_CODIGO = PJT.PRO_PAD_IN_CODIGO AND
      IPF.PRO_TAB_IN_CODIGO = PJT.PRO_TAB_IN_CODIGO