  SELECT DFC.ORG_IN_CODIGO,
       DFC.LAN_SEQ_IN_CODIGO,
       DFC.LAN_IN_CODIGO,
       decode(DEB_BO_CAIXABANCO, 'S', DFC.FIL_IN_CODIGODEB, DFC.FIL_IN_CODIGOCRE) FIL_IN_CODIGO,
       DFC.LAN_DT_LANCAMENTO,
       DFC.PLA_TAB_IN_CODIGO,
       DFC.PLA_PAD_IN_CODIGO,
       decode(DEB_BO_CAIXABANCO, 'S', DEB_IDE_ST_CODIGO, CRE_IDE_ST_CODIGO) CAIXA_IDE_ST_CODIGO,
       decode(DEB_BO_CAIXABANCO, 'S', DEB_IN_REDUZIDO, CRE_IN_REDUZIDO) CAIXA_IN_REDUZIDO,
       decode(DEB_BO_CAIXABANCO, 'N', DEB_IDE_ST_CODIGO, CRE_IDE_ST_CODIGO) CPT_IDE_ST_CODIGO,
       decode(DEB_BO_CAIXABANCO, 'N', DEB_IN_REDUZIDO, CRE_IN_REDUZIDO) CPT_IN_REDUZIDO,
       decode(DEB_BO_CAIXABANCO, 'S', CAIXA_RE_VALOR, 0) CAIXADEB_RE_VALOR,
       decode(DEB_BO_CAIXABANCO, 'N', CAIXA_RE_VALOR, 0) CAIXACRE_RE_VALOR,
       DFC.TLA_IN_CODIGO,
       DFC.LAN_CH_TIPOCONTAB
  FROM (select LDEB.ORG_IN_CODIGO,
               LDEB.LAN_SEQ_IN_CODIGO,
               LDEB.LAN_IN_CODIGO,
               LDEB.FIL_IN_CODIGO FIL_IN_CODIGODEB,
               LCRE.FIL_IN_CODIGO FIL_IN_CODIGOCRE,
               L.LAN_DT_LANCAMENTO,
               LDEB.PLA_TAB_IN_CODIGO,
               LDEB.PLA_PAD_IN_CODIGO,
               LDEB.DEB_IDE_ST_CODIGO,
               LDEB.DEB_IN_REDUZIDO,
               LCRE.CRE_IDE_ST_CODIGO,
               LCRE.CRE_IN_REDUZIDO,
               PDEB.PLA_BO_CAIXABANCO DEB_BO_CAIXABANCO,
               PCRE.PLA_BO_CAIXABANCO CRE_BO_CAIXABANCO,
               least(LDEB.ITE_RE_VALOR, LCRE.ITE_RE_VALOR) CAIXA_RE_VALOR,
               L.TLA_IN_CODIGO,
               L.LAN_CH_TIPOCONTAB
          from CONSTRUCAO.CON_LANCAMENTO@HACASA L,
               CONSTRUCAO.CON_ITEM_LANCAMENTO@HACASA LDEB,
               CONSTRUCAO.CON_ITEM_LANCAMENTO@HACASA LCRE,
               CONSTRUCAO.CON_PLANO_CONTA@HACASA PDEB,
               CONSTRUCAO.CON_PLANO_CONTA@HACASA PCRE
         where L.ORG_TAB_IN_CODIGO = LDEB.ORG_TAB_IN_CODIGO
           and L.ORG_PAD_IN_CODIGO = LDEB.ORG_PAD_IN_CODIGO
           and L.ORG_IN_CODIGO     = LDEB.ORG_IN_CODIGO
           and L.ORG_TAU_ST_CODIGO = LDEB.ORG_TAU_ST_CODIGO
           and L.LAN_TAB_IN_CODIGO = LDEB.LAN_TAB_IN_CODIGO
           and L.LAN_SEQ_IN_CODIGO = LDEB.LAN_SEQ_IN_CODIGO
           and L.LAN_IN_CODIGO     = LDEB.LAN_IN_CODIGO
           and LDEB.ORG_TAB_IN_CODIGO = LCRE.ORG_TAB_IN_CODIGO
           and LDEB.ORG_PAD_IN_CODIGO = LCRE.ORG_PAD_IN_CODIGO
           and LDEB.ORG_IN_CODIGO     = LCRE.ORG_IN_CODIGO
           and LDEB.ORG_TAU_ST_CODIGO = LCRE.ORG_TAU_ST_CODIGO
           and LDEB.LAN_TAB_IN_CODIGO = LCRE.LAN_TAB_IN_CODIGO
           and LDEB.LAN_SEQ_IN_CODIGO = LCRE.LAN_SEQ_IN_CODIGO
           and LDEB.LAN_IN_CODIGO     = LCRE.LAN_IN_CODIGO
           and LDEB.PLA_TAB_IN_CODIGO = PDEB.PLA_TAB_IN_CODIGO
           and LDEB.PLA_PAD_IN_CODIGO = PDEB.PLA_PAD_IN_CODIGO
           and LDEB.DEB_IDE_ST_CODIGO = PDEB.PLA_IDE_ST_CODIGO
           and LDEB.DEB_IN_REDUZIDO   = PDEB.PLA_IN_REDUZIDO
           and LCRE.PLA_TAB_IN_CODIGO = PCRE.PLA_TAB_IN_CODIGO
           and LCRE.PLA_PAD_IN_CODIGO = PCRE.PLA_PAD_IN_CODIGO
           and LCRE.CRE_IDE_ST_CODIGO = PCRE.PLA_IDE_ST_CODIGO
           and LCRE.CRE_IN_REDUZIDO   = PCRE.PLA_IN_REDUZIDO
           and L.LAN_CH_STATUS        = 'A'
           and (   (    PDEB.PLA_BO_CAIXABANCO = 'S'
                    and PCRE.PLA_BO_CAIXABANCO = 'N')
                or (    PDEB.PLA_BO_CAIXABANCO = 'N'
                    and PCRE.PLA_BO_CAIXABANCO = 'S'))) DFC