 SELECT LAN.ORG_TAB_IN_CODIGO,
     LAN.ORG_PAD_IN_CODIGO,
     LAN.ORG_IN_CODIGO,
     LAN.ORG_TAU_ST_CODIGO,
     LAN.LAN_TAB_IN_CODIGO,
     LAN.LAN_SEQ_IN_CODIGO,
     LAN.LAN_IN_CODIGO,
     LAN.IND_IN_CODIGO,
     LAN.ACAO_TAB_IN_CODIGO,
     LAN.ACAO_PAD_IN_CODIGO,
     LAN.ACAO_IN_CODIGO,
     LAN.ACAOM_ORG_IN_CODIGO,
     LAN.ACAOM_IN_SEQUENCIA,
     LAN.LOT_TAB_IN_CODIGO,
     LAN.LOT_SEQ_IN_CODIGO,
     LAN.LOT_IN_CODIGO,
     LAN.LAN_CH_STATUS,
     ITE.LAN_DT_LANCAMENTO,
     LAN.LAN_RE_TOTDEBITO,
     LAN.LAN_RE_TOTCREDITO,
     LAN.SIS_IN_CODIGO,
     LAN.TLA_IN_CODIGO,
     LAN.LAN_IN_ANOMES,
     LAN.LAN_IN_LANCMES,
     LAN.LAN_DT_IMPORTACAO,
     'C' LAN_CH_NATUREZA,
     ITE.ITE_IN_CODIGO,
     ITE.FIL_IN_CODIGO,
     ITE.ITE_DT_CONVERSAO,
     ITE.ITE_RE_VALOR,
     ITE.PLA_TAB_IN_CODIGO,
     ITE.PLA_PAD_IN_CODIGO,
     ITE.CRE_IDE_ST_CODIGO PLA_IDE_ST_CODIGO,
     ITE.CRE_IN_REDUZIDO   PLA_IN_REDUZIDO,
     ITE.CPT_IDE_ST_CODIGO,
     ITE.CPT_IN_REDUZIDO,
     ITE.ITE_CH_CONCBAN,
     ITE.ITE_CH_CONCCON,
     ITE.USU_IN_INCLUSAO,
     ITE.ITE_DT_INCLUSAO,
     ITE.USU_IN_ALTERACAO,
     ITE.ITE_DT_ULTALTERACAO,
     ITE.HIS_TAB_IN_CODIGO,
     ITE.HIS_PAD_IN_CODIGO,
     ITE.HIS_IDE_ST_CODIGO,
     ITE.HIS_IN_REDUZIDO,
     ITE.ITE_ST_COMPLEMENTO,
     ITE.ITE_ST_DOCUMENTO,
     ITE.ITE_ST_CONCILIACAO,
     ITE.ITE_ST_REFERENCIA,
     ITE.ITE_IN_ORIGEM,
     ITE.ITE_ST_DOCORIGEM,
     ITE.RECURDEB_TAB_IN_CODIGO,
     ITE.RECURDEB_PAD_IN_CODIGO,
     ITE.RECURDEB_IN_CODIGO,
     ITE.RECURCRE_TAB_IN_CODIGO,
     ITE.RECURCRE_PAD_IN_CODIGO,
     ITE.RECURCRE_IN_CODIGO,
     ITE.ITE_DT_ORCAMENTO,
     ITE.TPD_ST_CODIGO,
     LOT.LOT_CH_STATUS,
     LOT.LOT_BO_ABERTURA,
     LOT.LOT_CH_TIPO_LOTE,
     LOT.LOT_ST_DESCRICAO,
     LOT.LOT_DT_INICIAL,
     LOT.LOT_DT_FINAL,
     LOT.LOT_RE_TOTDEBITO,
     LOT.LOT_RE_TOTCREDITO,
     LOT.LOT_IN_NIVEL,
     LOT.LOT_ST_ORDEM,
     LOT.PAI_ORG_TAB_IN_CODIGO,
     LOT.PAI_ORG_PAD_IN_CODIGO,
     LOT.PAI_ORG_IN_CODIGO,
     LOT.PAI_ORG_TAU_ST_CODIGO,
     LOT.PAI_LOT_TAB_IN_CODIGO,
     LOT.PAI_LOT_SEQ_IN_CODIGO,
     LOT.PAI_LOT_IN_CODIGO,
     AGE.AGN_TAB_IN_CODIGO,
     AGE.AGN_PAD_IN_CODIGO,
     AGE.AGN_TAU_ST_CODIGO,
     AGE.AGN_IN_CODIGO,
     CON.CON_IN_SEQCONCCONT,
     TRUNC(CON.CON_DT_CONCILIACAO) as CON_DT_CONCILIACAOTRUNC, --JFB 10/05/2013 PM706094
     CON.CON_DT_MAIORDATA
FROM
     CONSTRUCAO.CON_LANCAMENTO@HACASA      LAN,
     CONSTRUCAO.CON_ITEM_LANCAMENTO@HACASA ITE,
     CONSTRUCAO.CON_LOTE@HACASA            LOT,
     CONSTRUCAO.GLO_CONTASAGENTES@HACASA AGE,
     CONSTRUCAO.GLO_CONTAS_ORG@HACASA CTA,
     CONSTRUCAO.CON_CONCBANCMOVIMENTO@HACASA CON
    WHERE ITE.ORG_TAB_IN_CODIGO = LAN.ORG_TAB_IN_CODIGO
 AND ITE.ORG_PAD_IN_CODIGO = LAN.ORG_PAD_IN_CODIGO
 AND ITE.ORG_IN_CODIGO     = LAN.ORG_IN_CODIGO
 And ITE.ORG_TAU_ST_CODIGO = LAN.ORG_TAU_ST_CODIGO
 AND ITE.LAN_TAB_IN_CODIGO = LAN.LAN_TAB_IN_CODIGO
 AND ITE.LAN_SEQ_IN_CODIGO = LAN.LAN_SEQ_IN_CODIGO
 AND ITE.LAN_IN_CODIGO     = LAN.LAN_IN_CODIGO
 AND LOT.ORG_TAB_IN_CODIGO = LAN.ORG_TAB_IN_CODIGO
 AND LOT.ORG_PAD_IN_CODIGO = LAN.ORG_PAD_IN_CODIGO
 And LOT.ORG_IN_CODIGO     = LAN.ORG_IN_CODIGO
 AND LOT.ORG_TAU_ST_CODIGO = LAN.ORG_TAU_ST_CODIGO
 AND LOT.LOT_TAB_IN_CODIGO = LAN.LOT_TAB_IN_CODIGO
 AND LOT.LOT_SEQ_IN_CODIGO = LAN.LOT_SEQ_IN_CODIGO
 AND LOT.LOT_IN_CODIGO     = LAN.LOT_IN_CODIGO
 AND ITE.PLA_TAB_IN_CODIGO = AGE.PLA_TAB_IN_CODIGO
 And ITE.PLA_PAD_IN_CODIGO = AGE.PLA_PAD_IN_CODIGO
 AND ITE.CRE_IDE_ST_CODIGO = AGE.PLA_IDE_ST_CODIGO
 AND ITE.CRE_IN_REDUZIDO = AGE.PLA_IN_REDUZIDO
 AND AGE.AGN_TAB_IN_CODIGO = CTA.AGN_TAB_IN_CODIGO
 AND AGE.AGN_PAD_IN_CODIGO = CTA.AGN_PAD_IN_CODIGO
 AND AGE.AGN_IN_CODIGO = CTA.AGN_IN_CODIGO
 And AGE.AGN_TAU_ST_CODIGO = CTA.AGN_TAU_ST_CODIGO
 AND CTA.ORG_TAB_IN_CODIGO = ITE.ORG_TAB_IN_CODIGO
 AND CTA.ORG_PAD_IN_CODIGO = ITE.ORG_PAD_IN_CODIGO
 AND CTA.ORG_TAU_ST_CODIGO = ITE.ORG_TAU_ST_CODIGO
 AND CTA.ORG_IN_CODIGO = ITE.FIL_IN_CODIGO
 And ITE.CRE_IDE_ST_CODIGO is not null
 AND LAN.LAN_CH_STATUS     = 'A'
 AND NOT (LAN.TLA_IN_CODIGO in (3, 5))
 AND ITE.CON_IN_SEQCONCCONT = CON.CON_IN_SEQCONCCONT(+)
UNION
SELECT
     LAN.ORG_TAB_IN_CODIGO,
     LAN.ORG_PAD_IN_CODIGO,
     LAN.ORG_IN_CODIGO,
     LAN.ORG_TAU_ST_CODIGO,
     LAN.LAN_TAB_IN_CODIGO,
     LAN.LAN_SEQ_IN_CODIGO,
     LAN.LAN_IN_CODIGO,
     LAN.IND_IN_CODIGO,
     LAN.ACAO_TAB_IN_CODIGO,
     LAN.ACAO_PAD_IN_CODIGO,
     LAN.ACAO_IN_CODIGO,
     LAN.ACAOM_ORG_IN_CODIGO,
     LAN.ACAOM_IN_SEQUENCIA,
     LAN.LOT_TAB_IN_CODIGO,
     LAN.LOT_SEQ_IN_CODIGO,
     LAN.LOT_IN_CODIGO,
     LAN.LAN_CH_STATUS,
     ITE.LAN_DT_LANCAMENTO,
     LAN.LAN_RE_TOTDEBITO,
     LAN.LAN_RE_TOTCREDITO,
     LAN.SIS_IN_CODIGO,
     LAN.TLA_IN_CODIGO,
     LAN.LAN_IN_ANOMES,
     LAN.LAN_IN_LANCMES,
     LAN.LAN_DT_IMPORTACAO,
     'D' LAN_CH_NATUREZA,
     ITE.ITE_IN_CODIGO,
     ITE.FIL_IN_CODIGO,
     ITE.ITE_DT_CONVERSAO,
     ITE.ITE_RE_VALOR,
     ITE.PLA_TAB_IN_CODIGO,
     ITE.PLA_PAD_IN_CODIGO,
     ITE.DEB_IDE_ST_CODIGO PLA_IDE_ST_CODIGO,
     ITE.DEB_IN_REDUZIDO   PLA_IN_REDUZIDO,
     ITE.CPT_IDE_ST_CODIGO,
     ITE.CPT_IN_REDUZIDO,
     ITE.ITE_CH_CONCBAN,
     ITE.ITE_CH_CONCCON,
     ITE.USU_IN_INCLUSAO,
     ITE.ITE_DT_INCLUSAO,
     ITE.USU_IN_ALTERACAO,
     ITE.ITE_DT_ULTALTERACAO,
     ITE.HIS_TAB_IN_CODIGO,
     ITE.HIS_PAD_IN_CODIGO,
     ITE.HIS_IDE_ST_CODIGO,
     ITE.HIS_IN_REDUZIDO,
     ITE.ITE_ST_COMPLEMENTO,
     ITE.ITE_ST_DOCUMENTO,
     ITE.ITE_ST_CONCILIACAO,
     ITE.ITE_ST_REFERENCIA,
     ITE.ITE_IN_ORIGEM,
     ITE.ITE_ST_DOCORIGEM,
     ITE.RECURDEB_TAB_IN_CODIGO,
     ITE.RECURDEB_PAD_IN_CODIGO,
     ITE.RECURDEB_IN_CODIGO,
     ITE.RECURCRE_TAB_IN_CODIGO,
     ITE.RECURCRE_PAD_IN_CODIGO,
     ITE.RECURCRE_IN_CODIGO,
     ITE.ITE_DT_ORCAMENTO,
     ITE.TPD_ST_CODIGO,
     LOT.LOT_CH_STATUS,
     LOT.LOT_BO_ABERTURA,
     LOT.LOT_CH_TIPO_LOTE,
     LOT.LOT_ST_DESCRICAO,
     LOT.LOT_DT_INICIAL,
     LOT.LOT_DT_FINAL,
     LOT.LOT_RE_TOTDEBITO,
     LOT.LOT_RE_TOTCREDITO,
     LOT.LOT_IN_NIVEL,
     LOT.LOT_ST_ORDEM,
     LOT.PAI_ORG_TAB_IN_CODIGO,
     LOT.PAI_ORG_PAD_IN_CODIGO,
     LOT.PAI_ORG_IN_CODIGO,
     LOT.PAI_ORG_TAU_ST_CODIGO,
     LOT.PAI_LOT_TAB_IN_CODIGO,
     LOT.PAI_LOT_SEQ_IN_CODIGO,
     LOT.PAI_LOT_IN_CODIGO,
     AGE.AGN_TAB_IN_CODIGO,
     AGE.AGN_PAD_IN_CODIGO,
     AGE.AGN_TAU_ST_CODIGO,
     AGE.AGN_IN_CODIGO,
     CON.CON_IN_SEQCONCCONT,
     trunc(CON.CON_DT_CONCILIACAO) as CON_DT_CONCILIACAOTRUNC, --JFB 10/05/2013 PM706094
     CON.CON_DT_MAIORDATA
FROM
     CONSTRUCAO.CON_LANCAMENTO@HACASA      LAN,
     CONSTRUCAO.CON_ITEM_LANCAMENTO@HACASA ITE,
     CONSTRUCAO.CON_LOTE@HACASA            LOT,
     CONSTRUCAO.GLO_CONTASAGENTES@HACASA AGE,
     CONSTRUCAO.GLO_CONTAS_ORG@HACASA CTA,
     CONSTRUCAO.CON_CONCBANCMOVIMENTO@HACASA CON
WHERE
     ITE.ORG_TAB_IN_CODIGO = LAN.ORG_TAB_IN_CODIGO
 AND ITE.ORG_PAD_IN_CODIGO = LAN.ORG_PAD_IN_CODIGO
 AND ITE.ORG_IN_CODIGO     = LAN.ORG_IN_CODIGO
 AND ITE.ORG_TAU_ST_CODIGO = LAN.ORG_TAU_ST_CODIGO
 AND ITE.LAN_TAB_IN_CODIGO = LAN.LAN_TAB_IN_CODIGO
 AND ITE.LAN_SEQ_IN_CODIGO = LAN.LAN_SEQ_IN_CODIGO
 And ITE.LAN_IN_CODIGO     = LAN.LAN_IN_CODIGO
 AND LOT.ORG_TAB_IN_CODIGO = LAN.ORG_TAB_IN_CODIGO
 AND LOT.ORG_PAD_IN_CODIGO = LAN.ORG_PAD_IN_CODIGO
 AND LOT.ORG_IN_CODIGO     = LAN.ORG_IN_CODIGO
 AND LOT.ORG_TAU_ST_CODIGO = LAN.ORG_TAU_ST_CODIGO
 AND LOT.LOT_TAB_IN_CODIGO = LAN.LOT_TAB_IN_CODIGO
 And LOT.LOT_SEQ_IN_CODIGO = LAN.LOT_SEQ_IN_CODIGO
 AND LOT.LOT_IN_CODIGO     = LAN.LOT_IN_CODIGO
 AND ITE.PLA_TAB_IN_CODIGO = AGE.PLA_TAB_IN_CODIGO
 AND ITE.PLA_PAD_IN_CODIGO = AGE.PLA_PAD_IN_CODIGO
 AND ITE.DEB_IDE_ST_CODIGO = AGE.PLA_IDE_ST_CODIGO
 AND ITE.DEB_IN_REDUZIDO = AGE.PLA_IN_REDUZIDO
 AND AGE.AGN_TAB_IN_CODIGO = CTA.AGN_TAB_IN_CODIGO
 AND AGE.AGN_PAD_IN_CODIGO = CTA.AGN_PAD_IN_CODIGO
 AND AGE.AGN_IN_CODIGO = CTA.AGN_IN_CODIGO
 AND AGE.AGN_TAU_ST_CODIGO = CTA.AGN_TAU_ST_CODIGO
 AND CTA.ORG_TAB_IN_CODIGO = ITE.ORG_TAB_IN_CODIGO
 And CTA.ORG_PAD_IN_CODIGO = ITE.ORG_PAD_IN_CODIGO
 AND CTA.ORG_TAU_ST_CODIGO = ITE.ORG_TAU_ST_CODIGO
 AND CTA.ORG_IN_CODIGO = ITE.FIL_IN_CODIGO
 AND ITE.DEB_IDE_ST_CODIGO is not null
 AND LAN.LAN_CH_STATUS     = 'A'
 AND NOT (LAN.TLA_IN_CODIGO in (3, 5))
 AND ITE.CON_IN_SEQCONCCONT = CON.CON_IN_SEQCONCCONT(+)