 SELECT L.LRAZ_IN_SEQUENCIA,
       PC.PLA_ST_EXTENSO,
       CC.CUS_ST_EXTENSO,
       PR.PRO_ST_EXTENSO,
       PC.PLA_PAD_IN_CODIGO,
       CC.CUS_PAD_IN_CODIGO,
       PR.PRO_PAD_IN_CODIGO
  FROM CONSTRUCAO.CON_LISTARAZAO@HACASA L,
       CONSTRUCAO.CON_PLANO_CONTA@HACASA PC,
       CONSTRUCAO.CON_CENTRO_CUSTO@HACASA CC,
       CONSTRUCAO.GLO_PROJETOS@HACASA PR
 WHERE L.LRAZ_CH_TIPO      = 'D'
   AND L.PLA_TAB_IN_CODIGO = PC.PLA_TAB_IN_CODIGO (+)
   AND L.PLA_PAD_IN_CODIGO = PC.PLA_PAD_IN_CODIGO (+)
   AND L.PLA_IDE_ST_CODIGO = PC.PLA_IDE_ST_CODIGO (+)
   AND L.PLA_IN_REDUZIDO   = PC.PLA_IN_REDUZIDO   (+)
   AND L.CUS_TAB_IN_CODIGO = CC.CUS_TAB_IN_CODIGO (+)
   AND L.CUS_PAD_IN_CODIGO = CC.CUS_PAD_IN_CODIGO (+)
   AND L.CUS_IDE_ST_CODIGO = CC.CUS_IDE_ST_CODIGO (+)
   AND L.CUS_IN_REDUZIDO   = CC.CUS_IN_REDUZIDO   (+)
   AND L.PRO_TAB_IN_CODIGO = PR.PRO_TAB_IN_CODIGO (+)
   AND L.PRO_PAD_IN_CODIGO = PR.PRO_PAD_IN_CODIGO (+)
   AND L.PRO_IDE_ST_CODIGO = PR.PRO_IDE_ST_CODIGO (+)
   AND L.PRO_IN_REDUZIDO   = PR.PRO_IN_REDUZIDO   (+)