  select cto.ORG_TAB_IN_CODIGO||'|'||cto.ORG_PAD_IN_CODIGO||'|'||cto.ORG_IN_CODIGO||'|'||cto.ORG_TAU_ST_CODIGO||'|'||cto.CTO_IN_CODIGO AS ID_CONTRATO,
       cli.AGN_TAB_IN_CODIGO||'|'||cli.AGN_PAD_IN_CODIGO||'|'||cli.AGN_IN_CODIGO||'|'||cli.AGN_TAU_ST_CODIGO AS ID_AGENTE,
       cto.AGNCFI_TAB_IN_CODIGO||'|'||CTO.AGNCFI_PAD_IN_CODIGO||'|'||CTO.AGNCFI_IN_CODIGO||'|'||CTO.AGNCFI_TAU_ST_CODIGO AS ID_CONTAFIN,
       cto.cus_TAB_IN_CODIGO||'|'||cto.cus_PAD_IN_CODIGO||'|'||cto.cus_IDE_ST_CODIGO||'|'||cto.cus_IN_REDUZIDO AS ID_CCUSTO,
       cto.PRO_TAB_IN_CODIGO||'|'||cto.PRO_PAD_IN_CODIGO||'|'||cto.PRO_IDE_ST_CODIGO||'|'||cto.PRO_IN_REDUZIDO AS ID_PROJETO,
       est.ORG_TAB_IN_CODIGO||'|'||est.ORG_PAD_IN_CODIGO||'|'||est.ORG_IN_CODIGO||'|'||est.ORG_TAU_ST_CODIGO||'|'||est.UND_IN_CODIGO AS ID_UNIDADE,

       EST.EMP_IN_CODIGO,
       EST.EMP_ST_CODIGO,
       EST.EMP_ST_NOME,
       EST.ETP_IN_CODIGO,
       EST.ETP_ST_CODIGO,
       EST.ETP_ST_NOME,
       EST.BLO_IN_CODIGO,
       EST.BLO_ST_CODIGO,
       EST.BLO_ST_NOME,
       EST.BLO_IN_NUMANDARES,
       EST.BLO_IN_NUMUNIDADES,
       EST.BLO_BO_ENDERECOPROPRIO,
       EST.BLO_DT_INICIOOBRA,
       EST.BLO_DT_LANCAMENTO,
       EST.UND_IN_CODIGO,
       EST.UND_ST_CODIGO,
       EST.UND_ST_NOME,
       EST.UND_ST_MATRICULA,
       EST.UND_ST_REGMATRICULA,
       EST.UND_IN_ANDAR,
       EST.UND_CH_STATUS,
       EST.UND_RE_PESO,
       EST.UND_RE_AREAPRIVATIVA,
       EST.UND_RE_FRACAO,
       EST.UND_RE_AREACOMUM,
       EST.UND_RE_AREATERRACO,
       EST.UND_RE_AREAGARAGEM,
       EST.UND_RE_AREAOUTROS,
       EST.UND_RE_AREATOTAL,
       EST.UND_ST_BOX,
       EST.UND_BO_ENDERECOPROPRIO,

       EST.ESTRUTURA,

       cto.ORG_IN_CODIGO AS COD_ORGANIZACAO,
       cto.FIL_IN_CODIGO AS COD_FILIAL,

       cto.cto_in_codigo,

       cto.cto_re_valorcontrato,
       cto.cto_re_valorcontrato_ori,
       cto.cto_re_mora,
       cto.cto_re_juros,
       cto.cto_re_totalresiduo,

       cto.cto_dt_cadastro,
       cto.cto_dt_entrega,
       CTO.CTO_DT_ENTREGA_REAL,
       CTO.CTO_DT_ENTCHAVES,

       CTO.CTO_BO_CESSAODIR,
       CTO.CTO_BO_DACAOPAGTERRENO,
       CTO.CTO_BO_FLUXOCAIXA,
       CTO.CTO_BO_JUROSSAC,
       CTO.CTO_BO_OPFANDAMENTO,
       CTO.CTO_BO_PATRIMONIOAFETACAO,
       CTO.CTO_BO_SINCRONIZADO,
       CTO.CTO_BO_STATUSSAC,
       CTO.CTO_BO_STATUSTP,
       CTO.CTO_BO_TABELAPRICE,
       CTO.CTO_BO_WEB,
       CTO.CND_IN_CODIGO,
       CTO.CTO_BO_ETIQUETA,
       CTO.CTO_BO_SELECIONADO,
       CTO.CTO_DT_STATUS,
       CTO.CTO_BO_IMPRESSO,
       CTO.CTO_DT_IMPRESSAO,
       CTO.CTO_RE_TABELAPRICE,
       CTO.CTO_DT_GERACAOTP,
       CTO.CTO_DT_REFERENCIATP,
       CTO.CTO_BO_PRORATA,
       CTO.CTO_BO_PRORATABX,
       CTO.CTO_ST_PATH_TEXTO,
       CTO.CTO_RE_TAXAANT,
       CTO.CTO_ST_OBSERVACAO,
       CTO.PRO_TAB_IN_CODIGO,
       CTO.PRO_PAD_IN_CODIGO,
       CTO.PRO_IDE_ST_CODIGO,
       CTO.PRO_IN_REDUZIDO,
       CTO.CUS_TAB_IN_CODIGO,
       CTO.CUS_PAD_IN_CODIGO,
       CTO.CUS_IDE_ST_CODIGO,
       CTO.CUS_IN_REDUZIDO,
       CTO.PAI_CTO_IN_CODIGO,
       CTO.CTO_BO_CONTABILIZA,
       CTO.CTO_BO_DESCPRORATA,
       CTO.CTO_IN_INDICE,
       CTO.CTO_BO_DESCONTOHBK,
       CTO.TEA_ST_CODIGO,
       CTO.CTO_RE_SALDOANTERIOR,
       CTO.CTO_DT_IMPORTACAO,
       CTO.CTO_DT_CLASSIFICACAO,
       CTO.CTO_RE_TAXARENEG,
       CTO.CTO_BO_PRORATA_ATRASO,
       CTO.CTO_DT_ASSINATURA,
       CTO.CTO_ST_CODBANCO,
       CTO.CTO_BO_VINCULA,
       CTO.CSF_IN_CODIGO,
       CTO.CTO_RE_TOTALRESIDUO_BKP,
       CTO.CTO_CH_REAJUSTEANUAL,
       CTO.CTO_IN_INDATRASO,
       CTO.CTO_RE_TAXAANTWEB_SAC,
       CTO.CTO_RE_TAXAANTWEB_TP,
       CTO.CTO_BO_TAXAEMPR,
       CTO.CTO_RE_TAXARESIDUO,
       CTO.CTO_IN_CARENCIAATRASO,
       CTO.CTO_BO_ENVIACORRECAODIA,
       CTO.CTO_CH_TIPOCALCULOMORA,
       CTO.CTO_IN_INDMORA,
       CTO.CTO_IN_MULTTAXAMORA,
       CTO.CTO_RE_AVALIACAO,
       CTO.CTO_DT_AVALIACAO,
       CTO.IND_IN_AVALIACAO,
       CTO.CTO_RE_MULTTAXAMORA,
       CTO.CTO_IN_DEFASINDICE,
       CTO.CTO_IN_DEFASINDATRASO,
       CTO.CTO_IN_DEFASINDMORA,
       CTO.CTO_IN_DEFASINDAVAL,
       CTO.CTO_BO_CORRIGERESCOB,
       CTO.CTO_BO_RESIDUOVMATRASO,
       CTO.CTO_BO_QUITACTO,
       CTO.CTO_BO_REUTILIZAINDICE,
       CTO.CTO_RE_PERCPERMUTA,
       CTO.CTO_DT_CLAUSULASUSP,
       CTO.CTO_BO_RESCOBENCARGOS,
       CTO.HCON_IN_SEQUENCIA,
       CTO.HCOB_IN_SEQUENCIA,
       CTO.AGNCFI_TAB_IN_CODIGO,
       CTO.AGNCFI_PAD_IN_CODIGO,
       CTO.AGNCFI_IN_CODIGO,
       CTO.AGNCFI_TAU_ST_CODIGO,
       CTO.CTO_BO_PRORATA_MESPGTO,
       CTO.CTO_BO_PRORATA_SOATRASO,
       CTO.CTO_BO_MAIORFATORDIS,
       CTO.CTO_BO_MAIORFATORATRASO,
       CTO.CTO_BO_MAIORFATORMORA,
       CTO.CTO_BO_MAIORFATORAVAL,
       CTO.CTO_IN_INDDESCAP,
       CTO.CTO_BO_ESCRITURA,
       CTO.CTO_ST_PATH_ESCRITURA,
       CTO.CTO_BO_CONGJURO,
       CTO.CTO_BO_DEFASAGEM_FIXA,
       CTO.CTO_IN_DEFASAGEM_FIXA,
       CTO.CTO_BO_VLTAXENCARGOS,
       CTO.CTO_RE_TAXAVP,
       CTO.CTO_DT_ESCRITURA,
       CTO.CTO_RE_TAXAANT_TP,
       CTO.COB_ST_CODIGO,
       CTO.CTO_DT_GERACAOSAC,
       CTO.CTO_DT_REFERENCIASAC,
       CTO.CTO_RE_TAXAANT_SAC,
       CTO.OPL_IN_CODIGO,
       CTO.CTO_RE_TAXABONIF_TP,
       CTO.CTO_RE_TAXABONIF_SAC,
       CTO.CTO_RE_LIMDESC,
       CTO.CTO_RE_TAXABONIFWEB_TP,
       CTO.CTO_RE_TAXABONIFWEB_SAC,
       CTO.CTO_CH_CONTABILIZAALUGUEL,
       CTO.CTO_BO_ATUALIZASEC,
       CTO.CTO_BO_CALCULAJROATEVCTO,
       CTO.CTO_IN_INDICEPARCATR,
       CTO.CTO_BO_INDPARCATRDEF,
       CTO.CTO_IN_INDPARCATRDEF,
       CTO.CTO_RE_TAXAANTWEB,
       CTO.CTO_RE_TAXABONIFWEB,
       CTO.CTO_BO_CONSIDSPED,
       CTO.CTO_BO_CALCTPNEW,
       CTO.CTO_BO_REMESSAJURIDICO,
       CTO.CTO_CH_PRORATA_ANIVERPARC,
       CTO.ID_INTEGRACAO,
       CTO.CTO_BO_MANTEMVOCORRNEG,
       CTO.CTO_BO_SPEDCONSDISTVENCPAR,
       CTO.CTO_BO_AGRUPAPARCMENSAL,
       CTO.CTO_BO_DESCONGPARCREAJANTEC,
       CTO.CTO_CH_CONTABILIZACAOALUGUEL,
       CTO.CTO_BO_VIGENCIAPRORATA,
       CTO.CTO_BO_ENVIAREGISTRADORA,

       DECODE(UPPER(CTO.CTO_CH_CLASSIFICACAO),
              'C', 'COMPRA E VENDA',
              'D', 'CONFISSÃO DE DÍVIDA',
              'A', 'ADITIVO',
              'P', 'ESCRITURA PÚBLICA',
              'R', 'ESCRITURA PARTICULAR',
              'OUTRO') AS CTO_CH_CLASSIFICACAO,

       DECODE(UPPER(CTO.CTO_CH_FORMAAPURACAO),
              'C', 'CUMULATIVO',
              'N', 'NÃO-CUMULATIVO',
              'OUTRO') AS CTO_CH_FORMAAPURACAO,

       CTO.CTO_CH_INTEGRADO_CRM,
       DECODE(UPPER(CTO.CTO_CH_ORIGEM),
              'T', 'TRANSFERÊNCIA',
              'C', 'CESSÃO DE DIREITOS',
              'OUTRO') AS CTO_CH_ORIGEM,

       DECODE(UPPER(CTO.CTO_CH_STATUS),
              'A', 'ATIVO',
              'U', 'INADIMPLENTE',
              'D', 'DISTRATADO',
              'T', 'TRANSFERIDO',
              'C', 'CESSÃO DE DIREITOS',
              'Q', 'QUITADO',
              'OUTRO') AS CTO_CH_STATUS,

       DECODE(UPPER(CTO.CTO_CH_TIPO),
              'P', 'PERMUTA',
              'V', 'VENDA',
              'M', 'ALUGUEL',
              'OUTRO') AS CTO_CH_TIPO,

       DECODE(UPPER(CTO.CTO_CH_TIPOJUROSRESIDUO),
              'S', 'JUROS SIMPLES',
              'C', 'JUROS COMPOSTOS',
              'OUTRO') AS CTO_CH_TIPOJUROSRESIDUO,

       DECODE(UPPER(CTO.CTO_CH_TIPOMULTA),
              'S', 'JUROS SIMPLES',
              'C', 'JUROS COMPOSTOS',
              'OUTRO') AS CTO_CH_TIPOMULTA

  from CONSTRUCAO.CAR_CONTRATO@HACASA cto

join CONSTRUCAO.car_contrato_cliente@HACASA cli on
  (cli.org_tab_in_codigo = cto.org_tab_in_codigo AND
   cli.org_pad_in_codigo = cto.org_pad_in_codigo AND
   cli.org_in_codigo     = cto.org_in_codigo AND
   cli.org_tau_st_codigo = cto.org_tau_st_codigo AND
   cli.cto_in_codigo     = cto.cto_in_codigo)

left join CONSTRUCAO.VW_CAR_ESTRUTURA@HACASA EST on
  (est.cto_org_tab_in_codigo = cto.org_tab_in_codigo AND
   est.cto_org_pad_in_codigo = cto.org_pad_in_codigo AND
   est.cto_org_in_codigo     = cto.org_in_codigo AND
   est.cto_org_tau_st_codigo = cto.org_tau_st_codigo AND
   est.cto_in_codigo         = cto.cto_in_codigo)