  SELECT HIS.HIS_TAB_IN_CODIGO||'|'||HIS.HIS_PAD_IN_CODIGO||'|'||HIS.HIS_IDE_ST_CODIGO||'|'||HIS.HIS_IN_REDUZIDO AS ID_HISTORICO,
       HIS.PAI_HIS_TAB_IN_CODIGO||'|'||HIS.PAI_HIS_PAD_IN_CODIGO||'|'||HIS.PAI_HIS_IDE_ST_CODIGO||'|'||HIS.PAI_HIS_IN_REDUZIDO AS ID_HISTORICO_PAI,
       HIS.HIS_IN_REDUZIDO AS COD_HISTORICO,
       HIS.HIS_ST_EXTENSO AS EXTENSO_HISTORICO,
       HIS.HIS_CH_TIPO_CONTA AS ANALITICO_SINTETICO,
       HIS.HIS_IN_NIVEL AS NIVEL_DO_EXTENSO,
       HIS.HIS_ST_APELIDO AS APELIDO,
       HIS.HIS_ST_DESCRICAO AS DESCRICAO
  FROM CONSTRUCAO.CON_HISTORICO@HACASA HIS