SELECT L.LAN_IN_SEQUENCIAL,
       L.VIS_IN_SEQUENCIAL,
       V.VIS_IN_CODIGO,
       L.PMES_IN_SEQUENCIAL,
       PMES.PMES_ST_CODIGO,
       L.ORG_IN_SEQUENCIAL,
       O.ORG_ST_CODIGO,
       L.LAN_IN_CODIGO,
       PGP.PGP_IN_SEQUENCIAL,
       PGP.PGP_IN_CODIGO,
       L.PDEB_IN_SEQUENCIAL,
       PDEB.PGER_ST_EXTENSO PDEB_ST_EXTENSO,
       PDEB.PGER_ST_DESCRICAO PDEB_ST_DESCRICAO,
       nvl2(PDEB.PGER_ST_EXTENSO, PDEB.PGER_ST_EXTENSO || ' - ' || PDEB.PGER_ST_DESCRICAO, null) PDEB_ST_DESCRICAOEXTENSO,
       PDEB.PGER_CH_NATUREZA PDEB_CH_NATUREZA,
       L.PCRE_IN_SEQUENCIAL,
       PCRE.PGER_ST_EXTENSO PCRE_ST_EXTENSO,
       PCRE.PGER_ST_DESCRICAO PCRE_ST_DESCRICAO,
       nvl2(PCRE.PGER_ST_EXTENSO, PCRE.PGER_ST_EXTENSO || ' - ' || PCRE.PGER_ST_DESCRICAO, null) PCRE_ST_DESCRICAOEXTENSO,
       PCRE.PGER_CH_NATUREZA PCRE_CH_NATUREZA,
       L.LAN_ST_HISTORICO,
       L.LAN_RE_VALOR,
       L.LAN_BO_AUTOMATICO
  FROM CONSTRUCAO.CBA_LANCAMENTO@HACASA L,
       CONSTRUCAO.CBA_PLANOGERPAD@HACASA PGP,
       CONSTRUCAO.CBA_PLANOGER@HACASA PDEB,
       CONSTRUCAO.CBA_PLANOGER@HACASA PCRE,
       CONSTRUCAO.CBA_PERIODOMES@HACASA PMES,
       CONSTRUCAO.CBA_ORGANIZACAO@HACASA O,
       CONSTRUCAO.CBA_VISAO@HACASA V
 WHERE L.PDEB_IN_SEQUENCIAL = PDEB.PGER_IN_SEQUENCIAL (+)
   AND L.PCRE_IN_SEQUENCIAL = PCRE.PGER_IN_SEQUENCIAL (+)
   AND L.PMES_IN_SEQUENCIAL = PMES.PMES_IN_SEQUENCIAL
   AND L.ORG_IN_SEQUENCIAL  = O.ORG_IN_SEQUENCIAL
   AND L.VIS_IN_SEQUENCIAL  = V.VIS_IN_SEQUENCIAL
   AND nvl(PDEB.PGP_IN_SEQUENCIAL, PCRE.PGP_IN_SEQUENCIAL) = PGP.PGP_IN_SEQUENCIAL