 SELECT ALC.NUMERO_DOCUMENTO, ALC.PAI_NUMERO_DOCUMENTO AS NUM_CONT, ALC.NOME_FILIAL, ALC.NOME_AGENTE, ALC.NOME_SOLICITANTE, ALC.VALOR_DOCUMENTO, ALC.DATA_DOCUMENTO, ALC.DATA_VENCIMENTO, ALC.STATUS_DOCUMENTO, FL.QTDE_APROVACAO, FL.NIVEL_APROVACAO, APR.NOME_APROVADOR, APR.PRIORIDADE_APROV, APR.DATA_DISPONIVEL
FROM CONSTRUCAO.WGLO_ALCADA_DOCUMENTO@HACASA ALC,
CONSTRUCAO.WGLO_ALCADA_FLUXO_DOCUMENTO@HACASA FL,
CONSTRUCAO.WGLO_ALCADA_FLUXO_APROVADOR@HACASA APR
WHERE ALC.DOC_IN_CODIGO = FL.DOC_IN_CODIGO AND
     FL.FLX_IN_CODIGO = APR.FLX_IN_CODIGO