 SELECT M.ORG_TAB_IN_CODIGO||'|'||M.ORG_PAD_IN_CODIGO||'|'||M.ORG_IN_CODIGO||'|'||M.ORG_TAU_ST_CODIGO||'|'||M.MOV_TAB_IN_CODIGO||'|'||M.MOV_SEQ_IN_CODIGO||'|'||M.MOV_IN_NUMLANCTO AS ID_CONTASRECEBER,

       M.AGN_TAB_IN_CODIGO||'|'||M.AGN_PAD_IN_CODIGO||'|'||M.AGN_IN_CODIGO||'|'||M.AGN_TAU_ST_CODIGO AS ID_AGENTE,
       M.ACAO_TAB_IN_CODIGO||'|'||M.ACAO_PAD_IN_CODIGO||'|'||M.ACAO_IN_CODIGO AS ID_ACAO,
       DECODE(M.HIS_IN_REDUZIDO, NULL, NULL, M.HIS_TAB_IN_CODIGO||'|'||M.HIS_PAD_IN_CODIGO||'|'||M.HIS_IDE_ST_CODIGO||'|'||M.HIS_IN_REDUZIDO) AS ID_HISTORICO,

       M.ORG_IN_CODIGO AS COD_ORGANIZACAO,
       M.FIL_IN_CODIGO AS COD_FILIAL,
       M.TREF_ST_CODIGO AS TIPO_CRECEBER,
       M.TPD_ST_CODIGO AS TIPO_DOCUMENTO,
       M.MOV_ST_DOCUMENTO AS DOCUMENTO,
       M.MOV_DT_DATADOCTO AS DATA_DOCUMENTO,
       M.MOV_DT_DATAINC AS DATA_INCLUSAO,
       M.MOV_DT_VENCTO AS VENCIMENTO,
       M.MOV_DT_PRORROGADO AS VENCIMENTO_PRORROGADO,

       M.IND_IN_CODIGOIND AS COD_INDICE,
       M.IND_IN_CODIGOMOE AS COD_MOEDA,
       M.MOV_RE_COTACAOMOE AS COTACAO_MOEDA,
       M.USU_IN_INCLUSAO AS COD_USUARIO_INCLUSAO,

       M.MOV_IN_NUMLANCTO AS NUMLANCTO,
       AGE.AGE_ST_NUMERO AS AGENCIA,
       M.AGN_PAD_IN_CODIGO AS PADRAO_AGENTE,
       M.AGN_IN_CODIGO AS COD_AGENTE,
       M.AGN_TAU_ST_CODIGO AS TIPO_AGENTE,
       M.MOV_BO_PREVISAO AS PREVISAO,
       M.ACAO_PAD_IN_CODIGO AS PADRAO_ACAO,
       M.ACAO_IN_CODIGO AS COD_ACAO,
       M.ACAOM_IN_SEQUENCIA AS ACAOM_IN_SEQUENCIA,
       TCOB.TCOB_ST_DESCRICAO AS TIPO_COBRANCA,
       M.BAN_IN_NUMERO AS NUMERO_BANCO,
       M.MOV_ST_PARCELA AS PARCELA,
       M.HIS_PAD_IN_CODIGO AS PADRAO_HISTORICO,
       M.HIS_IN_REDUZIDO AS COD_HISTORICO,
       SCOB.SCOB_ST_DESCRICAO AS SITUACAO_COBRANCA,
       M.MOV_ST_HBKSTATUS AS STATUS_HBK,
       M.MOV_DT_ORCAMENTO AS DATA_ORCAMENTO,
       M.MOV_RE_SALDOCPACRE AS SALDO_CRE,
       M.MOV_RE_VALORMOEDA AS VALOR_MOEDA,
       R.FRE_TPD_ST_CODIGO AS TIPO_DOCUMENTO_FATURA,
       R.FRE_IN_NUMERO AS NUMERO_FATURA,
       R.CRE_RE_PERCJUROSEFET AS PERCENTUAL_JUROS,
       R.CRE_RE_VRMORAEFET AS VALOR_MORA,
       R.CRE_RE_PERCMULTAEFET AS PERCENTUAL_MULTA,
       R.CRE_RE_VRMULTAEFET AS VALOR_MULTA,
       R.CRE_RE_PERCDESCEFET AS PERCENTUAL_DESCONTO,
       R.CRE_RE_VRDESCCONDEFET AS VALOR_DESCONTO,
       R.CRE_DT_DTBASEMULTA AS DATA_BASE_MULTA,
       R.CRE_DT_DTBASEDESC AS DATA_BASE_DESCONTO,
       R.CRE_ST_SITUACAOHBK AS SITUACAO_HBK,
       R.CRE_RE_PERCDESCEFET2 AS PERCENTUAL_DESCONTO2,
       R.CRE_RE_VRDESCCONDEFET2 AS VALOR_DESCONTO2,
       R.CRE_DT_DTBASEDESC2 AS DATA_BASE_DESCONTO2,
       HCOB.HCOB_ST_DESCRICAO AS DESCRICAO_COBRANCA_HBK,
       F.FRE_ST_DOCTOINTERNO AS DOCUMENTO_INTERNO,
       R.CRE_RE_VRJUROSBAIXA AS VALOR_JUROS_BAIXA
  FROM CONSTRUCAO.FIN_MOVIMENTO@HACASA M

JOIN CONSTRUCAO.FIN_CONTASRECEBER@HACASA R ON
  (R.ORG_TAB_IN_CODIGO  = M.ORG_TAB_IN_CODIGO AND
   R.ORG_PAD_IN_CODIGO  = M.ORG_PAD_IN_CODIGO AND
   R.ORG_IN_CODIGO      = M.ORG_IN_CODIGO AND
   R.ORG_TAU_ST_CODIGO  = M.ORG_TAU_ST_CODIGO AND
   R.MOV_TAB_IN_CODIGO  = M.MOV_TAB_IN_CODIGO AND
   R.MOV_SEQ_IN_CODIGO  = M.MOV_SEQ_IN_CODIGO AND
   R.MOV_IN_NUMLANCTO   = M.MOV_IN_NUMLANCTO)

JOIN CONSTRUCAO.FIN_FATURARECEBER@HACASA F ON
  (F.ORG_TAB_IN_CODIGO  = R.ORG_TAB_IN_CODIGO AND
   F.ORG_PAD_IN_CODIGO  = R.ORG_PAD_IN_CODIGO AND
   F.ORG_IN_CODIGO      = R.ORG_IN_CODIGO AND
   F.ORG_TAU_ST_CODIGO  = R.ORG_TAU_ST_CODIGO AND
   F.SER_TAB_IN_CODIGO  = R.SER_TAB_IN_CODIGO AND
   F.SER_ST_CODIGO      = R.SER_ST_CODIGO AND
   F.SER_IN_SEQUENCIA   = R.SER_IN_SEQUENCIA AND
   F.FRE_TPD_ST_CODIGO  = R.FRE_TPD_ST_CODIGO AND
   F.FRE_IN_NUMERO      = R.FRE_IN_NUMERO)

LEFT JOIN CONSTRUCAO.FIN_HBKCOBRANCA@HACASA HCOB ON
  (HCOB.HCOB_IN_SEQUENCIA = R.HCOB_IN_SEQUENCIA)

LEFT JOIN CONSTRUCAO.FIN_TIPOCOBR@HACASA TCOB ON
  (TCOB.TCOB_ST_CODIGO = M.TCOB_ST_CODIGO)

LEFT JOIN CONSTRUCAO.FIN_SITCOBR@HACASA SCOB ON
  (SCOB.SCOB_ST_CODIGO = M.SCOB_ST_CODIGO)

LEFT JOIN CONSTRUCAO.GLO_AGENCIA@HACASA AGE ON
  (AGE.BAN_IN_NUMERO = M.BAN_IN_NUMERO AND
   AGE.AGE_IN_CODIGO = M.AGE_IN_CODIGO)

WHERE M.MOV_CH_SITUACAO    = 'N'
AND   M.MOV_CH_STATUSBXREF = 'N'
AND   M.MOV_CH_ORIGEM      = 'R'