 SELECT R.ORG_TAB_IN_CODIGO||'|'||R.ORG_PAD_IN_CODIGO||'|'||R.ORG_IN_CODIGO||'|'||R.ORG_TAU_ST_CODIGO||'|'||R.MOV_TAB_IN_CODIGO||'|'||R.MOV_SEQ_IN_CODIGO||'|'||R.MOV_IN_NUMLANCTO AS ID_MOV_VINCULADO,
       
       LCL.CLA_TAB_IN_CODIGO||'|'||LCL.CLA_PAD_IN_CODIGO||'|'||LCL.CLA_IDE_ST_CODIGO||'|'||LCL.CLA_IN_REDUZIDO AS ID_CLASSE,
       LCC.CCF_TAB_IN_CODIGO||'|'||LCC.CCF_PAD_IN_CODIGO||'|'||LCC.CCF_IDE_ST_CODIGO||'|'||LCC.CCF_IN_REDUZIDO AS ID_CCUSTO,
       LPR.PRO_TAB_IN_CODIGO||'|'||LPR.PRO_PAD_IN_CODIGO||'|'||LPR.PRO_IDE_ST_CODIGO||'|'||LPR.PRO_IN_REDUZIDO AS ID_PROJETO,
       
       LPR.LPR_RE_VALOR AS VALOR,
       LPR.LPR_RE_VALORCRE AS VALOR_CREDITO,
       LPR.LPR_RE_VALORDEB AS VALOR_DEBITO,
       LCL.LCL_CH_NATUREZA AS NATUREZA

  FROM CONSTRUCAO.FIN_MOVIMENTO@HACASA V

JOIN CONSTRUCAO.FIN_REFERENCIAFIN@HACASA R ON
  (R.ORG_TAB_IN_CODIGO = V.ORG_TAB_IN_CODIGO AND
   R.ORG_PAD_IN_CODIGO = V.ORG_PAD_IN_CODIGO AND
   R.ORG_IN_CODIGO     = V.ORG_IN_CODIGO AND
   R.ORG_TAU_ST_CODIGO = V.ORG_TAU_ST_CODIGO AND
   R.MOV_TAB_IN_CODIGO = V.MOV_TAB_IN_CODIGO AND
   R.MOV_SEQ_IN_CODIGO = V.MOV_SEQ_IN_CODIGO AND
   R.MOV_IN_NUMLANCTO  = V.MOV_IN_NUMLANCTO)

JOIN CONSTRUCAO.FIN_MOVIMENTO@HACASA M ON
  (M.ORG_TAB_IN_CODIGO = R.REF_ORG_TAB_IN_CODIGO AND
   M.ORG_PAD_IN_CODIGO = R.REF_ORG_PAD_IN_CODIGO AND
   M.ORG_IN_CODIGO     = R.REF_ORG_IN_CODIGO AND
   M.ORG_TAU_ST_CODIGO = R.REF_ORG_TAU_ST_CODIGO AND
   M.MOV_TAB_IN_CODIGO = R.REF_MOV_TAB_IN_CODIGO AND
   M.MOV_SEQ_IN_CODIGO = R.REF_MOV_SEQ_IN_CODIGO AND
   M.MOV_IN_NUMLANCTO  = R.REF_MOV_IN_NUMLANCTO)

LEFT JOIN CONSTRUCAO.FIN_LANCCLASSE@HACASA LCL ON
  (LCL.ORG_TAB_IN_CODIGO = V.ORG_TAB_IN_CODIGO AND
   LCL.ORG_PAD_IN_CODIGO = V.ORG_PAD_IN_CODIGO AND
   LCL.ORG_IN_CODIGO     = V.ORG_IN_CODIGO AND
   LCL.ORG_TAU_ST_CODIGO = V.ORG_TAU_ST_CODIGO AND
   LCL.MOV_TAB_IN_CODIGO = V.MOV_TAB_IN_CODIGO AND
   LCL.MOV_SEQ_IN_CODIGO = V.MOV_SEQ_IN_CODIGO AND
   LCL.MOV_IN_NUMLANCTO  = V.MOV_IN_NUMLANCTO)

LEFT JOIN CONSTRUCAO.FIN_LANCCCUSTO@HACASA LCC ON
  (LCC.ORG_TAB_IN_CODIGO = LCL.ORG_TAB_IN_CODIGO AND
   LCC.ORG_PAD_IN_CODIGO = LCL.ORG_PAD_IN_CODIGO AND
   LCC.ORG_IN_CODIGO     = LCL.ORG_IN_CODIGO AND
   LCC.ORG_TAU_ST_CODIGO = LCL.ORG_TAU_ST_CODIGO AND
   LCC.MOV_TAB_IN_CODIGO = LCL.MOV_TAB_IN_CODIGO AND
   LCC.MOV_SEQ_IN_CODIGO = LCL.MOV_SEQ_IN_CODIGO AND
   LCC.MOV_IN_NUMLANCTO  = LCL.MOV_IN_NUMLANCTO AND
   LCC.CLA_TAB_IN_CODIGO = LCL.CLA_TAB_IN_CODIGO AND
   LCC.CLA_PAD_IN_CODIGO = LCL.CLA_PAD_IN_CODIGO AND
   LCC.CLA_IDE_ST_CODIGO = LCL.CLA_IDE_ST_CODIGO AND
   LCC.CLA_IN_REDUZIDO   = LCL.CLA_IN_REDUZIDO AND
   LCC.LCL_CH_NATUREZA   = LCL.LCL_CH_NATUREZA)

LEFT JOIN CONSTRUCAO.FIN_LANCPROJ@HACASA LPR ON
  (LPR.ORG_TAB_IN_CODIGO = LCC.ORG_TAB_IN_CODIGO AND
   LPR.ORG_PAD_IN_CODIGO = LCC.ORG_PAD_IN_CODIGO AND
   LPR.ORG_IN_CODIGO     = LCC.ORG_IN_CODIGO AND
   LPR.ORG_TAU_ST_CODIGO = LCC.ORG_TAU_ST_CODIGO AND
   LPR.MOV_TAB_IN_CODIGO = LCC.MOV_TAB_IN_CODIGO AND
   LPR.MOV_SEQ_IN_CODIGO = LCC.MOV_SEQ_IN_CODIGO AND
   LPR.MOV_IN_NUMLANCTO  = LCC.MOV_IN_NUMLANCTO AND
   LPR.CLA_TAB_IN_CODIGO = LCC.CLA_TAB_IN_CODIGO AND
   LPR.CLA_PAD_IN_CODIGO = LCC.CLA_PAD_IN_CODIGO AND
   LPR.CLA_IDE_ST_CODIGO = LCC.CLA_IDE_ST_CODIGO AND
   LPR.CLA_IN_REDUZIDO   = LCC.CLA_IN_REDUZIDO AND
   LPR.LCL_CH_NATUREZA   = LCC.LCL_CH_NATUREZA AND
   LPR.LCC_IN_NUMERO     = LCC.LCC_IN_NUMERO)

WHERE M.MOV_CH_SITUACAO    = 'N'   
AND   M.MOV_CH_STATUSBXREF = 'N'
AND   M.MOV_CH_ORIGEM      = 'P'
AND   V.MOV_CH_SITUACAO    = 'N'
AND   V.MOV_CH_STATUSBXREF = 'N'