SELECT DISTINCT M.ORG_TAB_IN_CODIGO||'|'||M.ORG_PAD_IN_CODIGO||'|'||M.ORG_IN_CODIGO||'|'||M.ORG_TAU_ST_CODIGO||'|'||M.MOV_TAB_IN_CODIGO||'|'||M.MOV_SEQ_IN_CODIGO||'|'||M.MOV_IN_NUMLANCTO AS ID_MOVFIN,

       M.AGN_TAB_IN_CODIGO||'|'||M.AGN_PAD_IN_CODIGO||'|'||M.AGN_IN_CODIGO||'|'||M.AGN_TAU_ST_CODIGO AS ID_AGENTE,
       M.ACAO_TAB_IN_CODIGO||'|'||M.ACAO_PAD_IN_CODIGO||'|'||M.ACAO_IN_CODIGO AS ID_ACAO,
       DECODE(M.HIS_IN_REDUZIDO, NULL, NULL, M.HIS_TAB_IN_CODIGO||'|'||M.HIS_PAD_IN_CODIGO||'|'||M.HIS_IDE_ST_CODIGO||'|'||M.HIS_IN_REDUZIDO) AS ID_HISTORICO,

       M.ORG_IN_CODIGO AS COD_ORGANIZACAO,
       M.FIL_IN_CODIGO AS COD_FILIAL,
       R.REF_ST_TIPO AS TIPO_MOVFIN,
       M.TPD_ST_CODIGO AS TIPO_DOCUMENTO,
       M.MOV_ST_DOCUMENTO AS DOCUMENTO,
       M.MOV_DT_DATADOCTO AS DATA_DOCUMENTO,
       M.MOV_DT_DATAINC AS DATA_INCLUSAO,
       M.MOV_DT_VENCTO AS VENCIMENTO,
       M.MOV_DT_PRORROGADO AS VENCIMENTO_PRORROGADO,

       M.MOV_CH_NATUREZA AS NATUREZA_PRINCIPAL, /*VERIFICAR USO PRÁTICO DESSA COLUNA*/

       M.IND_IN_CODIGOIND AS COD_INDICE,
       M.IND_IN_CODIGOMOE AS COD_MOEDA,
       M.MOV_RE_COTACAOMOE AS COTACAO_MOEDA,
       M.USU_IN_INCLUSAO AS COD_USUARIO_INCLUSAO,

       M.MOV_IN_NUMLANCTO AS NUMLANCTO,
       M.AGN_PAD_IN_CODIGO AS PADRAO_AGENTE,
       M.AGN_IN_CODIGO AS COD_AGENTE,
       M.AGN_TAU_ST_CODIGO AS TIPO_AGENTE,
       M.ACAO_PAD_IN_CODIGO AS PADRAO_ACAO,
       M.ACAO_IN_CODIGO AS COD_ACAO,
       M.ACAOM_IN_SEQUENCIA AS ACAOM_IN_SEQUENCIA,
       M.BAN_IN_NUMERO AS NUMERO_BANCO,
       M.HIS_PAD_IN_CODIGO AS PADRAO_HISTORICO,
       M.HIS_IN_REDUZIDO AS COD_HISTORICO,
       M.MOV_DT_ORCAMENTO AS DATA_ORCAMENTO,
       M.MOV_RE_VALORMOEDA AS VALOR_MOEDA

  FROM CONSTRUCAO.FIN_MOVIMENTO@HACASA M

LEFT JOIN CONSTRUCAO.FIN_REFERENCIAFIN@HACASA R ON
  (R.ORG_TAB_IN_CODIGO = M.ORG_TAB_IN_CODIGO AND
   R.ORG_PAD_IN_CODIGO = M.ORG_PAD_IN_CODIGO AND
   R.ORG_IN_CODIGO     = M.ORG_IN_CODIGO AND
   R.ORG_TAU_ST_CODIGO = M.ORG_TAU_ST_CODIGO AND
   R.MOV_TAB_IN_CODIGO = M.MOV_TAB_IN_CODIGO AND
   R.MOV_SEQ_IN_CODIGO = M.MOV_SEQ_IN_CODIGO AND
   R.MOV_IN_NUMLANCTO  = M.MOV_IN_NUMLANCTO)

WHERE M.MOV_CH_ORIGEM   = 'M'
AND   M.MOV_CH_SITUACAO = 'N'
AND   (M.TREF_ST_CODIGO IS NULL OR M.TREF_ST_CODIGO = 'TRANSF')