SELECT IND.IND_IN_CODIGO AS CÓD,
NOM.IND_ST_SIGLA AS SIGLA,
NOM.IND_ST_NOME AS NOME_INDICE,
IND.VAL_DT_INDICE AS DATA,
IND.VAL_RE_VALOR AS VALOR,
DECODE(UPPER(NOM.IND_CH_DIASUTEIS),
              'S', 'SIM',
              'N', 'NÃO'
              ) AS DIAS_UTEIS,
DECODE(UPPER(NOM.IND_CH_TIPOCORR),
              'M', 'MENSAL',
              'D', 'DIÁRIA'
              ) AS TIPO_CORREÇÃO,
DECODE(UPPER(IND.VAL_CH_TIPO),
              'R', 'REAL') AS REAL_OU_PROJETADO             
FROM CONSTRUCAO.GLO_VALOR_FINANCEIRO@HACASA IND,
     CONSTRUCAO.GLO_INDICE_FINANCEIRO@HACASA NOM
WHERE IND.IND_IN_CODIGO = NOM.IND_IN_CODIGO
