 select AM.ORG_TAB_IN_CODIGO,
       AM.ORG_PAD_IN_CODIGO,
       AM.ORG_IN_CODIGO,
       AM.ORG_TAU_ST_CODIGO,
       AM.ACAOM_IN_SEQUENCIA,
       AM.CONT_ORG_IN_CODIGO,
       AM.FIL_IN_CODIGO,
       AM.ACAO_TAB_IN_CODIGO,
       AM.ACAO_PAD_IN_CODIGO,
       AM.ACAO_IN_CODIGO,
       AM.ACAOM_ST_DOCUMENTO,
       AM.ACAOM_DT_DATAEMISSAO,
       AM.ACAOM_DT_DATAENTRADA,
       AM.USU_IN_INCLUSAO,
       AM.USU_IN_ALTERACAO,
       AM.USU_IN_EXCLUSAO,
       AM.ACAOM_DT_INCLUSAO,
       AM.ACAOM_DT_ALTERACAO,
       AM.ACAOM_DT_EXCLUSAO,
       AM.ACAOM_RE_VALORCONTABIL,
       AM.ACAOM_RE_VALORCONTABILREAL,
       AM.ACAOM_RE_VALORFISCAL,
       AM.ACAOM_RE_VALORFISCALREAL,
       AM.ACAOM_RE_VALORFINANC,
       AM.ACAOM_RE_VALORFINANCREAL,
       AM.ACAOM_RE_VALORIMOB,
       AM.ACAOM_RE_VALORIMOBREAL,
       AM.FORM_IN_ID,
       A.ACAO_ST_NOME,
       A.ACAO_ST_TIPO,
       A.ACAO_BO_CPAG,
       A.ACAO_ST_ENTSAI,
       A.ACAO_BO_CREC,
       A.ACAO_BO_MOVFIN,
       A.ACAO_BO_CONTAB,
       A.ACAO_BO_IMOB,
       A.ACAO_BO_FISCAL,
       A.ACAO_BO_DEVOLUCAO,
       A.ACAO_BO_ORCAMENTO,
       A.ACAO_BO_TRANSFERENCIA,
       INCL.GRU_ST_NOME USU_ST_NOMEINCLUSAO,
       ALT.GRU_ST_NOME USU_ST_NOMEALTERACAO,
       EXCL.GRU_ST_NOME USU_ST_NOMEEXCLUSAO
  from construcao.GLO_ACAOMOVIMENTO@hacasa AM,
       construcao.GLO_ACAO@hacasa A,
       construcao.GLO_GRUPO_USUARIO@hacasa INCL,
       construcao.GLO_GRUPO_USUARIO@hacasa ALT,
       (select GRU_IN_CODIGO, GRU_ST_NOME
        from   construcao.GLO_GRUPO_USUARIO@hacasa
        union
        select 0, null from dual) excl
 where A.ACAO_TAB_IN_CODIGO = AM.ACAO_TAB_IN_CODIGO
   and A.ACAO_PAD_IN_CODIGO = AM.ACAO_PAD_IN_CODIGO
   and A.ACAO_IN_CODIGO = AM.ACAO_IN_CODIGO
   and AM.USU_IN_INCLUSAO = INCL.GRU_IN_CODIGO
   and AM.USU_IN_ALTERACAO = ALT.GRU_IN_CODIGO
   and nvl(AM.USU_IN_EXCLUSAO, 0) = EXCL.GRU_IN_CODIGO