 SELECT PRO.PRO_TAB_IN_CODIGO||'|'||PRO.PRO_PAD_IN_CODIGO||'|'||PRO.PRO_IDE_ST_CODIGO||'|'||PRO.PRO_IN_REDUZIDO AS ID_PROJETO,
       PRO.PAI_PRO_TAB_IN_CODIGO||'|'||PRO.PAI_PRO_PAD_IN_CODIGO||'|'||PRO.PAI_PRO_IDE_ST_CODIGO||'|'||PRO.PAI_PRO_IN_REDUZIDO AS ID_PROJETO_PAI,
       PRO.PRO_IN_REDUZIDO AS COD_PROJETO,
       PRO.PRO_ST_EXTENSO AS EXTENSO_PROJETO,
       PRO.PRO_CH_ANASIN AS ANALITICO_SINTETICO,
       PRO.PRO_IN_NIVEL AS NIVEL_DO_EXTENSO,
       PRO.PRO_ST_APELIDO AS APELIDO,
       PRO.PRO_ST_DESCRICAO AS DESCRICAO
  FROM CONSTRUCAO.GLO_PROJETOS@HACASA PRO