  SELECT EST.EMP_ST_NOME,
       EST.CTO_ORG_TAB_IN_CODIGO,   
       EST.CTO_ORG_PAD_IN_CODIGO,
       EST.CTO_ORG_IN_CODIGO,
       EST.CTO_ORG_TAU_ST_CODIGO,
       EST.CTO_IN_CODIGO,
       SEG.ORG_TAB_IN_CODIGO,   
       SEG.ORG_PAD_IN_CODIGO,
       SEG.ORG_IN_CODIGO,
       SEG.ORG_TAU_ST_CODIGO,
       SEG.CTO_IN_CODIGO NÚMERO_CONTRATO,
       SEG.CTO_NOME_SEGUR NOME_SEGURADO,
       SEG.CTO_TIPO_IMOVEL TIPO_IMÓVEL,
       SEG.CTO_SEGURADORA SEGURADORA,
       SEG.CTO_VCTO_APOLICE VENCIMENTO_APÓLICE,
       SEG.CTO_COBERTURA VALOR_COBERTURA,
       SEG.CTO_VALOR_SIN COBERTURA
FROM CONSTRUCAO.CAR_CONTRATOCMPESP@HACASA SEG
JOIN CONSTRUCAO.VW_CAR_ESTRUTURA@HACASA EST on
  (EST.CTO_ORG_TAB_IN_CODIGO = SEG.ORG_TAB_IN_CODIGO AND
   EST.CTO_ORG_PAD_IN_CODIGO = SEG.ORG_PAD_IN_CODIGO AND
   EST.CTO_ORG_IN_CODIGO     = SEG.ORG_IN_CODIGO AND
   EST.CTO_ORG_TAU_ST_CODIGO = SEG.ORG_TAU_ST_CODIGO AND
   EST.CTO_IN_CODIGO         = SEG.CTO_IN_CODIGO);
