  SELECT 
   TBV.EST_IN_CODIGO,
   TBV.UND_RE_VALORUNIDADE,
   TBV.UND_DT_VIGENCIA,
   TBV.UND_DT_CADASTRO,
   TBV.VUN_CH_TIPO,
   TBV.VUN_IN_CODIGO,
   UND.UND_RE_AREATOTAL,
   TBV.UND_RE_VALORUNIDADE / UND.UND_RE_AREAPRIVATIVA AS VALOR_M2
FROM
   CONSTRUCAO.WCMR_VALOR_UNIDADE@HACASA TBV
JOIN
   CONSTRUCAO.DBM_UNIDADE@HACASA UND
ON
   TBV.ORG_TAB_IN_CODIGO = UND.ORG_TAB_IN_CODIGO AND
   TBV.ORG_PAD_IN_CODIGO = UND.ORG_PAD_IN_CODIGO AND
   TBV.ORG_IN_CODIGO = UND.ORG_IN_CODIGO AND
   TBV.ORG_TAU_ST_CODIGO = UND.ORG_TAU_ST_CODIGO AND
   TBV.EST_IN_CODIGO = UND.EST_IN_CODIGO