SELECT TREF.TREF_ST_CODIGO AS COD_TREF,
       TREF_ST_DESCRICAO AS DESCRICAO
  FROM CONSTRUCAO.FIN_TIPOREFERENCIA@HACASA TREF
WHERE EXISTS (SELECT 1 FROM CONSTRUCAO.FIN_REFERENCIAFIN@HACASA R
              WHERE R.REF_ST_TIPO = TREF.TREF_ST_CODIGO)