 SELECT  E.ORG_TAB_IN_CODIGO,
  E.ORG_PAD_IN_CODIGO,
  E.ORG_IN_CODIGO,
  E.ORG_TAU_ST_CODIGO,
  E.EST_IN_CODIGO,
  E.EST_CLASSIFICACAO_N1,
  E.EST_CLASSIFICACAO_N2,
  E.EST_CLASSIFICACAO_N3,
  E.EST_CLASSIFICACAO_N4,
  E.EST_TLU_COD,
  E.EST_VALOR_TLU,
  E.EST_DESC_TLU,
  E.EST_TLU_COB,
  E.EST_INSC_IMOB
  
  FROM 
  CONSTRUCAO.DBM_ESTRUTURACMPESP@HACASA E